// Package parser provides HTML parsing for the sfpg-go dashboard page.
// It extracts structured metrics from the dashboard HTML template
// using the testutil HTML parsing helpers.
//
// The parser handles the HTML structure generated by web/templates/dashboard.html.tmpl
// and extracts all stat values, module statuses, and cache configurations.
//
// # Example
//
//	resp, err := http.Get("http://localhost:8083/dashboard")
//	if err != nil {
//	    // handle error
//	}
//	defer resp.Body.Close()
//
//	metrics, err := parser.ParseDashboard(resp.Body)
//	if err != nil {
//	    if errors.Is(err, parser.ErrDashboardNotFound) {
//	        // dashboard container not found in response
//	    }
//	    // other parsing error
//	}
//
//	fmt.Println("Last Updated:", metrics.LastUpdated)
//	fmt.Println("Memory Allocated:", metrics.Memory.Allocated)
package parser
