// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package gallerydb

import (
	"context"
)

const getConfigValueByKey = `-- name: GetConfigValueByKey :one
SELECT value 
  FROM config
 WHERE key = ?
`

func (q *Queries) GetConfigValueByKey(ctx context.Context, key string) (string, error) {
	row := q.queryRow(ctx, q.getConfigValueByKeyStmt, getConfigValueByKey, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getConfigs = `-- name: GetConfigs :many
SELECT "key", value, created_at, updated_at, type, category, requires_restart, description, default_value, help_text, example_value
  FROM config
`

func (q *Queries) GetConfigs(ctx context.Context) ([]Config, error) {
	rows, err := q.query(ctx, q.getConfigsStmt, getConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
			&i.Category,
			&i.RequiresRestart,
			&i.Description,
			&i.DefaultValue,
			&i.HelpText,
			&i.ExampleValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConfigValueOnly = `-- name: UpsertConfigValueOnly :exec
INSERT INTO config (key, value, created_at, updated_at)
VALUES (?, ?, ?, ?)
    ON CONFLICT(key) 
    DO UPDATE SET value=excluded.value
                , updated_at=excluded.updated_at   
            WHERE value IS NOT excluded.value
`

type UpsertConfigValueOnlyParams struct {
	Key       string
	Value     string
	CreatedAt interface{}
	UpdatedAt interface{}
}

func (q *Queries) UpsertConfigValueOnly(ctx context.Context, arg UpsertConfigValueOnlyParams) error {
	_, err := q.exec(ctx, q.upsertConfigValueOnlyStmt, upsertConfigValueOnly,
		arg.Key,
		arg.Value,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
