// Package gallerydb provides the database access layer for the application.
// It uses sqlc to generate type-safe Go code from SQL queries. This package
// includes the generated code, custom queries, and data models.
package gallerydb

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"
	"strings"
	"sync/atomic"

	sqlcqueries "github.com/lbe/sfpg-go/sqlc/queries"
)

// BatchLoadTarget represents a single cache warm target from GetBatchLoadTargets.
type BatchLoadTarget struct {
	Path    string
	Variant string
}

// CustomQuerier extends the sqlc-generated Querier interface with custom
// hand-written query methods.
type CustomQuerier interface {
	Querier
	GetBatchLoadTargets(ctx context.Context) ([]BatchLoadTarget, error)
	GetFileViewRowsByFolderID(ctx context.Context, folderID int64) (*sql.Rows, error)
	GetFileViewRowsByFolderPath(ctx context.Context, folderPath string) (*sql.Rows, error)
	GetFolderViewThumbnailBlobDataByPath(ctx context.Context, path string) ([]byte, error)
	GetPreloadRoutesByFolderID(ctx context.Context, parent_id sql.NullInt64) ([]string, error)
	GetThumbnailBlobDataByID(ctx context.Context, thumbnailID int64) ([]byte, error)
	UpsertThumbnailBlob(ctx context.Context, arg UpsertThumbnailBlobParams) error
	// QueryFilesForFolderIndexRebuild streams every folder-bearing file ordered so
	// Go can compute per-folder navigation columns in one pass. It reads the files
	// table (which exists at pool init), so it is prepared at PrepareCustomQueries.
	QueryFilesForFolderIndexRebuild(ctx context.Context) (*sql.Rows, error)
	// CountFilesForFolderIndexRebuild returns the number of folder-bearing files
	// (same WHERE as the stream) so the rebuild can pre-size its pairs slice. It
	// reads the files table (which exists at pool init), so it is prepared at
	// PrepareCustomQueries.
	CountFilesForFolderIndexRebuild(ctx context.Context) (int64, error)
	// InsertFileFolderIndexNewRows bulk-inserts rows into file_folder_index_new. The
	// dest table is runtime CloneEmpty, so the INSERT is prepared on the batcher
	// transaction, not at pool Prepare. It requires WithTx (a non-nil tx).
	InsertFileFolderIndexNewRows(ctx context.Context, rows []InsertFileFolderIndexNewParams) error
	// FileFolderIndexNewExists reports whether the file_folder_index_new dest table
	// exists without executing an INSERT and without aborting the caller's tx when
	// the table is missing. Used by the writebatcher flush to skip index rows only.
	FileFolderIndexNewExists(ctx context.Context) (bool, error)
}

// CustomQueries embeds the sqlc-generated Queries struct and adds methods
// for custom, hand-written queries. All custom queries are prepared statements
// for consistency and performance.
type CustomQueries struct {
	*Queries
	// Custom prepared statements for queries that are not generated by sqlc.
	getBatchLoadTargetsStmt                  *sql.Stmt
	getFileViewRowsByFolderIDStmt            *sql.Stmt
	getFileViewRowsByFolderPathStmt          *sql.Stmt
	getFolderViewThumbnailBlobDataByPathStmt *sql.Stmt
	getPreloadRoutesByFolderIDStmt           *sql.Stmt
	getThumbnailBlobDataByIDStmt             *sql.Stmt
	upsertThumbnailBlobStmt                  *sql.Stmt
	// queryFilesForFolderIndexRebuildStmt streams files for the folder-index rebuild.
	// It reads the files table (exists at pool init), so it is prepared at
	// PrepareCustomQueries, unlike the dest INSERT below.
	queryFilesForFolderIndexRebuildStmt *sql.Stmt
	// countFilesForFolderIndexRebuildStmt counts folder-bearing files for the
	// folder-index rebuild pairs slice cap. It reads the files table (exists at
	// pool init), so it is prepared at PrepareCustomQueries.
	countFilesForFolderIndexRebuildStmt *sql.Stmt
}

// Ensure CustomQueries implements CustomQuerier.
var _ CustomQuerier = (*CustomQueries)(nil)

// NewCustomQueries creates a new CustomQueries instance without preparing statements.
// Use PrepareCustomQueries for statement preparation.
func NewCustomQueries(db DBTX) *CustomQueries {
	return &CustomQueries{
		Queries: New(db),
	}
}

var ct_prepares atomic.Int64

// PrepareCustomQueries prepares both the sqlc-generated statements and custom
// statements, returning a fully initialized CustomQueries object. It also attaches
// the thumbnail blob database for multi-database transaction consistency.
func PrepareCustomQueries(ctx context.Context, db DBTX) (*CustomQueries, error) {
	cq := &CustomQueries{
		Queries: &Queries{db: db},
	}

	// Prepare sqlc's statements
	queries, err := Prepare(ctx, db)
	if err != nil {
		return nil, err
	}
	cq.Queries = queries

	// Attach the thumbnail blob database schema for cross-DB consistency.
	// This allows ATTACH DATABASE to be used in queries for multi-database operations.
	// Note: The attachment is connection-scoped and must be established per connection.
	// The caller is responsible for providing the correct blob_db path or attaching dynamically.
	_ = db // Placeholder for future ATTACH logic if needed in PrepareContext

	// Prepare all custom statements
	if cq.getBatchLoadTargetsStmt, err = prepareContextFn(ctx, db, getBatchLoadTargets); err != nil {
		return nil, fmt.Errorf("error preparing query GetBatchLoadTargets: %w", err)
	}
	if cq.getFileViewRowsByFolderIDStmt, err = prepareContextFn(ctx, db, getFileViewRowsByFolderID); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileViewRowsByFolderID: %w", err)
	}
	if cq.getFileViewRowsByFolderPathStmt, err = prepareContextFn(ctx, db, getFileViewRowsByFolderPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileViewRowsByFolderPath: %w", err)
	}
	if cq.getFolderViewThumbnailBlobDataByPathStmt, err = prepareContextFn(ctx, db, getFolderViewThumbnailBlobDataByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetFolderViewThumbnailBlobDataByPath: %w", err)
	}
	if cq.getPreloadRoutesByFolderIDStmt, err = prepareContextFn(ctx, db, getPreloadRoutesByFolderID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPreloadRoutesByFolderID: %w", err)
	}
	if cq.getThumbnailBlobDataByIDStmt, err = prepareContextFn(ctx, db, getThumbnailBlobDataByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetThumbnailBlobDataByID: %w", err)
	}
	if cq.upsertThumbnailBlobStmt, err = prepareContextFn(ctx, db, upsertThumbnailBlob); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertThumbnailBlob: %w", err)
	}
	// Prepared at pool init because the files table exists then. The dest INSERT
	// (file_folder_index_new) is NOT prepared here because that table is runtime
	// CloneEmpty and would not yet exist.
	if cq.queryFilesForFolderIndexRebuildStmt, err = prepareContextFn(ctx, db, stripSQLComments(sqlcqueries.QueryFilesForFolderIndexRebuildSQL())); err != nil {
		return nil, fmt.Errorf("error preparing query QueryFilesForFolderIndexRebuild: %w", err)
	}
	if cq.countFilesForFolderIndexRebuildStmt, err = prepareContextFn(ctx, db, stripSQLComments(sqlcqueries.CountFilesForFolderIndexRebuildSQL())); err != nil {
		return nil, fmt.Errorf("error preparing query CountFilesForFolderIndexRebuild: %w", err)
	}

	ct_prepares.Add(1)
	slog.Debug("Prepared CustomQueries", "total_prepares", ct_prepares.Load())
	return cq, nil
}

// Close closes all prepared custom statements and delegates to the embedded Queries.Close().
func (cq *CustomQueries) Close() error {
	var errs []error

	if cq.getBatchLoadTargetsStmt != nil {
		if err := stmtCloseFn(cq.getBatchLoadTargetsStmt); err != nil {
			errs = append(errs, fmt.Errorf("error closing getBatchLoadTargetsStmt: %w", err))
		}
	}
	if cq.getFileViewRowsByFolderIDStmt != nil {
		if err := stmtCloseFn(cq.getFileViewRowsByFolderIDStmt); err != nil {
			errs = append(errs, fmt.Errorf("error closing getFileViewRowsByFolderIDStmt: %w", err))
		}
	}
	if cq.getFileViewRowsByFolderPathStmt != nil {
		if err := stmtCloseFn(cq.getFileViewRowsByFolderPathStmt); err != nil {
			errs = append(errs, fmt.Errorf("error closing getFileViewRowsByFolderPathStmt: %w", err))
		}
	}
	if cq.getFolderViewThumbnailBlobDataByPathStmt != nil {
		if err := stmtCloseFn(cq.getFolderViewThumbnailBlobDataByPathStmt); err != nil {
			errs = append(errs, fmt.Errorf("error closing getFolderViewThumbnailBlobDataByPathStmt: %w", err))
		}
	}
	if cq.getPreloadRoutesByFolderIDStmt != nil {
		if err := stmtCloseFn(cq.getPreloadRoutesByFolderIDStmt); err != nil {
			errs = append(errs, fmt.Errorf("error closing getPreloadRoutesByFolderIDStmt: %w", err))
		}
	}
	if cq.getThumbnailBlobDataByIDStmt != nil {
		if err := stmtCloseFn(cq.getThumbnailBlobDataByIDStmt); err != nil {
			errs = append(errs, fmt.Errorf("error closing getThumbnailBlobDataByIDStmt: %w", err))
		}
	}
	if cq.upsertThumbnailBlobStmt != nil {
		if err := stmtCloseFn(cq.upsertThumbnailBlobStmt); err != nil {
			errs = append(errs, fmt.Errorf("error closing upsertThumbnailBlobStmt: %w", err))
		}
	}
	if cq.queryFilesForFolderIndexRebuildStmt != nil {
		if err := stmtCloseFn(cq.queryFilesForFolderIndexRebuildStmt); err != nil {
			errs = append(errs, fmt.Errorf("error closing queryFilesForFolderIndexRebuildStmt: %w", err))
		}
	}
	if cq.countFilesForFolderIndexRebuildStmt != nil {
		if err := stmtCloseFn(cq.countFilesForFolderIndexRebuildStmt); err != nil {
			errs = append(errs, fmt.Errorf("error closing countFilesForFolderIndexRebuildStmt: %w", err))
		}
	}

	// Close the embedded Queries (which closes all its prepared statements).
	if qErr := cq.Queries.Close(); qErr != nil {
		errs = append(errs, fmt.Errorf("error closing embedded Queries: %w", qErr))
	}

	if len(errs) > 0 {
		for i, err := range errs {
			slog.Error("close error", "err", err, "index", i)
		}
		return errs[0]
	}
	return nil
}

// ============================================================================
// Custom Query SQL and Methods
// ============================================================================

const getBatchLoadTargets = `-- name: GetBatchLoadTargets :many
WITH cte_cache_map AS (
    SELECT 'folder' AS cache_type, '/gallery/'     AS cache_entry, 'full'            AS variant
    UNION ALL
    SELECT 'folder' AS cache_type, '/gallery/'     AS cache_entry, 'gallery-content' AS variant
    UNION ALL
    SELECT 'folder' AS cache_type, '/info/folder/' AS cache_entry, 'box_info'        AS variant
    UNION ALL
    SELECT 'file'   AS cache_type, '/info/image/'  AS cache_entry, 'box_info'        AS variant
    UNION ALL
    SELECT 'file'   AS cache_type, '/lightbox/'    AS cache_entry, 'lightbox-ui'     AS variant
),
cte_folders AS (
    SELECT b.cache_entry || f.id AS path, b.variant
      FROM folders f
      JOIN cte_cache_map b ON b.cache_type = 'folder'
),
cte_files AS (
    SELECT b.cache_entry || f.id AS path, b.variant
      FROM files f
      JOIN cte_cache_map b ON b.cache_type = 'file'
),
u AS (
    SELECT path, variant FROM cte_folders
    UNION ALL
    SELECT path, variant FROM cte_files
)
SELECT path, variant
  FROM u
 ORDER BY
  CASE
    WHEN path LIKE '/gallery/%' THEN 0
    WHEN path LIKE '/info/folder/%' THEN 1
    WHEN path LIKE '/info/image/%' THEN 2
    WHEN path LIKE '/lightbox/%' THEN 3
    ELSE 9
  END,
  path,
  variant`

// GetBatchLoadTargets returns all cache warm targets (gallery, info/folder, info/image, lightbox)
// in folders-first order for batch load.
func (cq *CustomQueries) GetBatchLoadTargets(ctx context.Context) ([]BatchLoadTarget, error) {
	rows, err := cq.query(ctx, cq.getBatchLoadTargetsStmt, getBatchLoadTargets)
	if err != nil {
		return nil, err
	}

	var out []BatchLoadTarget
	for rows.Next() {
		var t BatchLoadTarget
		if err := rows.Scan(&t.Path, &t.Variant); err != nil {
			return nil, err
		}
		out = append(out, t)
	}
	if err := rowsCloseFn(rows); err != nil {
		return nil, err
	}
	return out, rowsErrFn(rows)
}

const getFileViewRowsByFolderID = `-- name: GetFileViewRowsByFolderID :many
SELECT id, folder_id, folder_path, path, filename, size_bytes, md5, mime_type
     , width, height, created_at, updated_at 
  FROM file_view
 WHERE folder_id = ?
 ORDER BY filename`

// GetFileViewRowsByFolderID retrieves all files in a folder by folder ID.
func (cq *CustomQueries) GetFileViewRowsByFolderID(ctx context.Context, folderID int64) (*sql.Rows, error) {
	return cq.query(ctx, cq.getFileViewRowsByFolderIDStmt, getFileViewRowsByFolderID, folderID)
}

const getFileViewRowsByFolderPath = `-- name: GetFileViewRowsByFolderPath :many
SELECT id, folder_id, folder_path, path, filename, size_bytes, md5, mime_type
     , width, height, created_at, updated_at 
  FROM file_view
 WHERE folder_path = ?
 ORDER BY filename`

// GetFileViewRowsByFolderPath retrieves all files in a folder by folder path.
func (cq *CustomQueries) GetFileViewRowsByFolderPath(ctx context.Context, folderPath string) (*sql.Rows, error) {
	return cq.query(ctx, cq.getFileViewRowsByFolderPathStmt, getFileViewRowsByFolderPath, folderPath)
}

const getFolderViewThumbnailBlobDataByPath = `-- name: GetFolderViewThumbnailBlobDataByPath :one 
SELECT tb.data
  FROM folder_paths fp
       INNER JOIN folders f
               ON fp.id = f.path_id
       INNER JOIN thumbs.thumbnail_blobs tb 
               ON f.tile_id = tb.thumbnail_id
 WHERE fp.path = ?`

// GetFolderViewThumbnailBlobDataByPath retrieves the thumbnail blob for a folder's
// tile image directly via the folder path. This query joins the main DB with the
// thumbnail blob store.
func (cq *CustomQueries) GetFolderViewThumbnailBlobDataByPath(ctx context.Context, path string) ([]byte, error) {
	row := cq.queryRow(ctx, cq.getFolderViewThumbnailBlobDataByPathStmt, getFolderViewThumbnailBlobDataByPath, path)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getPreloadRoutesByFolderID = `-- name: GetPreloadRoutesByFolderID :many
WITH cte_cache_map AS (
    SELECT 'folder' AS cache_type, '/gallery/' AS cache_entry
    UNION ALL 
    SELECT 'folder' AS cache_type, '/info/folder/' AS cache_entry
    UNION ALL 
    SELECT 'file' AS cache_type, '/info/image/' AS cache_entry
    UNION ALL 
    SELECT 'file' AS cache_type, '/lightbox/' AS cache_entry
)
, cte_folders as (
    SELECT CASE WHEN f.parent_id IS NULL THEN 1 ELSE f.parent_id END AS parent_id, f.id AS folder_id, b.cache_entry || f.id as route 
      FROM folders f 
           INNER JOIN folders a 
                   ON f.parent_id = a.id 
           INNER JOIN cte_cache_map b 
                   ON b.cache_type = 'folder'
    UNION ALL 
    SELECT 1 AS parent_id, f.id AS folder_id, b.cache_entry || f.id as route 
      FROM folders f 
           CROSS JOIN cte_cache_map b 
                   ON b.cache_type = 'folder'
     WHERE f.parent_id is null 
)
, cte_files AS (
    SELECT CASE WHEN a.parent_id IS NULL THEN 1 ELSE a.parent_id END AS parent_id, f.folder_id, b.cache_entry || f.id as route
      FROM files f 
           INNER JOIN folders a 
                   ON f.folder_id = a.id 
           INNER JOIN cte_cache_map b 
                   ON b.cache_type = 'file'
)
, u AS (
    SELECT *
      FROM cte_folders
    UNION ALL
    SELECT *
      FROM cte_files
)
SELECT route 
  FROM u 
 WHERE ? IN (parent_id, folder_id)`

// GetPreloadRoutesByFolderID retrieves all preload routes for subfolders and files
// under the specified folder ID.
func (cq *CustomQueries) GetPreloadRoutesByFolderID(ctx context.Context, parent_id sql.NullInt64) ([]string, error) {
	rows, err := cq.query(ctx, cq.getPreloadRoutesByFolderIDStmt, getPreloadRoutesByFolderID, parent_id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var routes []string
	for rows.Next() {
		var route string
		if err := rows.Scan(&route); err != nil {
			return nil, err
		}
		routes = append(routes, route)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return routes, nil
}

const getThumbnailBlobDataByID = `-- name: GetThumbnailBlobDataByID :one
SELECT data
  FROM thumbs.thumbnail_blobs 
 WHERE thumbnail_id = ?`

// GetThumbnailBlobDataByID retrieves thumbnail blob data by thumbnail ID.
// This method is now on CustomQueries to support the separate blob database.
func (cq *CustomQueries) GetThumbnailBlobDataByID(ctx context.Context, thumbnailID int64) ([]byte, error) {
	row := cq.queryRow(ctx, cq.getThumbnailBlobDataByIDStmt, getThumbnailBlobDataByID, thumbnailID)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const upsertThumbnailBlob = `-- name: UpsertThumbnailBlob :exec
INSERT INTO thumbs.thumbnail_blobs (thumbnail_id, data)
VALUES (?, ?)
    ON CONFLICT(thumbnail_id) 
    DO UPDATE SET data = excluded.data
            WHERE data IS NOT excluded.data`

// UpsertThumbnailBlobParams are the parameters for upserting a thumbnail blob.
type UpsertThumbnailBlobParams struct {
	ThumbnailID int64
	Data        []byte
}

// UpsertThumbnailBlob inserts or updates thumbnail blob data by thumbnail ID.
// This method is now on CustomQueries to support the separate blob database.
func (cq *CustomQueries) UpsertThumbnailBlob(ctx context.Context, arg UpsertThumbnailBlobParams) error {
	_, err := cq.exec(ctx, cq.upsertThumbnailBlobStmt, upsertThumbnailBlob, arg.ThumbnailID, arg.Data)
	return err
}

// WithTx returns a new CustomQueries instance with the provided transaction,
// allowing custom queries to be executed within a transaction. All prepared
// statements are propagated to the transactional instance.
func (cq *CustomQueries) WithTx(tx *sql.Tx) *CustomQueries {
	return &CustomQueries{
		Queries:                                  cq.Queries.WithTx(tx),
		getBatchLoadTargetsStmt:                  cq.getBatchLoadTargetsStmt,
		getFileViewRowsByFolderIDStmt:            cq.getFileViewRowsByFolderIDStmt,
		getFileViewRowsByFolderPathStmt:          cq.getFileViewRowsByFolderPathStmt,
		getFolderViewThumbnailBlobDataByPathStmt: cq.getFolderViewThumbnailBlobDataByPathStmt,
		getPreloadRoutesByFolderIDStmt:           cq.getPreloadRoutesByFolderIDStmt,
		getThumbnailBlobDataByIDStmt:             cq.getThumbnailBlobDataByIDStmt,
		upsertThumbnailBlobStmt:                  cq.upsertThumbnailBlobStmt,
		queryFilesForFolderIndexRebuildStmt:      cq.queryFilesForFolderIndexRebuildStmt,
		countFilesForFolderIndexRebuildStmt:      cq.countFilesForFolderIndexRebuildStmt,
	}
}

// stripSQLComments removes leading SQL line comments (lines starting with --)
// from a statement so sqlite can prepare it. The -- name: directives and STREAMING
// notes are comments, not SQL. Inline comments inside the SELECT/INSERT body are
// not present in the embedded SQL, so a line-based strip is sufficient and safe.
func stripSQLComments(s string) string {
	lines := strings.Split(s, "\n")
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "--") {
			continue
		}
		out = append(out, line)
	}
	return strings.TrimSpace(strings.Join(out, "\n"))
}

// InsertFileFolderIndexNewParams are the column values for one file_folder_index_new row.
// prev_id/next_id are NullInt64 because the first/last file in a folder has no
// previous/next neighbor, expressed as NULL in SQL.
type InsertFileFolderIndexNewParams struct {
	FileID     int64
	FolderID   int64
	ImageIndex int64
	ImageCount int64
	PrevID     sql.NullInt64
	NextID     sql.NullInt64
	FirstID    int64
	LastID     int64
}

// QueryFilesForFolderIndexRebuild streams every folder-bearing file ordered by
// folder, filename, then id so the rebuild can compute per-folder navigation
// columns in Go without materializing all rows. The statement is prepared at
// PrepareCustomQueries because it reads the files table (exists at pool init).
func (cq *CustomQueries) QueryFilesForFolderIndexRebuild(ctx context.Context) (*sql.Rows, error) {
	return cq.query(ctx, cq.queryFilesForFolderIndexRebuildStmt, sqlcqueries.QueryFilesForFolderIndexRebuildSQL())
}

// CountFilesForFolderIndexRebuild returns the number of folder-bearing files,
// the same WHERE as the streaming SELECT. It is prepared at pool init because it
// reads the files table (exists at pool init).
func (cq *CustomQueries) CountFilesForFolderIndexRebuild(ctx context.Context) (int64, error) {
	var count int64
	if err := cq.countFilesForFolderIndexRebuildStmt.QueryRowContext(ctx).Scan(&count); err != nil {
		return 0, fmt.Errorf("count files for folder-index rebuild: %w", err)
	}
	return count, nil
}

// FileFolderIndexNewExists reports whether the file_folder_index_new dest table
// exists. It is a non-aborting existence check (sqlite_master is allowed inside
// gallerydb): when the table is missing it returns false with no error, so the
// writebatcher flush can skip index rows only and still commit File/Cache writes.
func (cq *CustomQueries) FileFolderIndexNewExists(ctx context.Context) (bool, error) {
	var exists int64
	err := cq.db.QueryRowContext(ctx,
		"SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='file_folder_index_new'").Scan(&exists)
	if err != nil {
		return false, fmt.Errorf("check file_folder_index_new existence: %w", err)
	}
	return exists > 0, nil
}

// InsertFileFolderIndexNewRows bulk-inserts rows into file_folder_index_new. It
// requires WithTx (cq.tx != nil): the dest table is runtime CloneEmpty, so the
// INSERT is prepared on the transaction exactly once (G6), then Exec'd per row
// up to MaxBatchSize. It never calls cq.tx.ExecContext with an SQL string.
func (cq *CustomQueries) InsertFileFolderIndexNewRows(ctx context.Context, rows []InsertFileFolderIndexNewParams) error {
	if cq.tx == nil {
		return fmt.Errorf("InsertFileFolderIndexNewRows requires WithTx (non-nil transaction)")
	}
	if len(rows) == 0 {
		return nil
	}
	stmt, err := prepareContextFn(ctx, cq.tx, stripSQLComments(sqlcqueries.InsertFileFolderIndexNewSQL()))
	if err != nil {
		return fmt.Errorf("prepare folder index insert: %w", err)
	}
	defer func() {
		if cerr := stmtCloseFn(stmt); cerr != nil {
			slog.Debug("close folder index insert stmt", "err", cerr)
		}
	}()
	for _, row := range rows {
		var prevID, nextID any
		if row.PrevID.Valid {
			prevID = row.PrevID.Int64
		} else {
			prevID = nil
		}
		if row.NextID.Valid {
			nextID = row.NextID.Int64
		} else {
			nextID = nil
		}
		if _, err := stmtExecContextFn(ctx, stmt,
			row.FileID, row.FolderID, row.ImageIndex, row.ImageCount,
			prevID, nextID, row.FirstID, row.LastID); err != nil {
			return fmt.Errorf("insert folder index row for file %d: %w", row.FileID, err)
		}
	}
	return nil
}
