// Package gallerydb provides the database access layer for the application.
// It uses sqlc to generate type-safe Go code from SQL queries. This package
// includes the generated code, custom queries, and data models.
package gallerydb

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"
	"sync/atomic"
)

// CustomQuerier extends the sqlc-generated Querier interface with custom
// hand-written query methods.
type CustomQuerier interface {
	Querier
	GetFileViewRowsByFolderID(ctx context.Context, folderID int64) (*sql.Rows, error)
	GetFileViewRowsByFolderPath(ctx context.Context, folderPath string) (*sql.Rows, error)
	GetFolderViewThumbnailBlobDataByPath(ctx context.Context, path string) ([]byte, error)
	GetPreloadRoutesByFolderID(ctx context.Context, parent_id sql.NullInt64) (*sql.Rows, error)
	GetThumbnailBlobDataByID(ctx context.Context, thumbnailID int64) ([]byte, error)
	UpsertThumbnailBlob(ctx context.Context, arg UpsertThumbnailBlobParams) error
}

// CustomQueries embeds the sqlc-generated Queries struct and adds methods
// for custom, hand-written queries. All custom queries are prepared statements
// for consistency and performance.
type CustomQueries struct {
	*Queries
	// Custom prepared statements for queries that are not generated by sqlc.
	getFileViewRowsByFolderIDStmt            *sql.Stmt
	getFileViewRowsByFolderPathStmt          *sql.Stmt
	getFolderViewThumbnailBlobDataByPathStmt *sql.Stmt
	getPreloadRoutesByFolderIDStmt           *sql.Stmt
	getThumbnailBlobDataByIDStmt             *sql.Stmt
	upsertThumbnailBlobStmt                  *sql.Stmt
}

// Ensure CustomQueries implements CustomQuerier.
var _ CustomQuerier = (*CustomQueries)(nil)

// NewCustomQueries creates a new CustomQueries instance without preparing statements.
// Use PrepareCustomQueries for statement preparation.
func NewCustomQueries(db DBTX) *CustomQueries {
	return &CustomQueries{
		Queries: New(db),
	}
}

var ct_prepares atomic.Int64

// PrepareCustomQueries prepares both the sqlc-generated statements and custom
// statements, returning a fully initialized CustomQueries object. It also attaches
// the thumbnail blob database for multi-database transaction consistency.
func PrepareCustomQueries(ctx context.Context, db DBTX) (*CustomQueries, error) {
	cq := &CustomQueries{
		Queries: &Queries{db: db},
	}

	// Prepare sqlc's statements
	queries, err := Prepare(ctx, db)
	if err != nil {
		return nil, err
	}
	cq.Queries = queries

	// Attach the thumbnail blob database schema for cross-DB consistency.
	// This allows ATTACH DATABASE to be used in queries for multi-database operations.
	// Note: The attachment is connection-scoped and must be established per connection.
	// The caller is responsible for providing the correct blob_db path or attaching dynamically.
	_ = db // Placeholder for future ATTACH logic if needed in PrepareContext

	// Prepare all custom statements
	if cq.getFileViewRowsByFolderIDStmt, err = db.PrepareContext(ctx, getFileViewRowsByFolderID); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileViewRowsByFolderID: %w", err)
	}
	if cq.getFileViewRowsByFolderPathStmt, err = db.PrepareContext(ctx, getFileViewRowsByFolderPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileViewRowsByFolderPath: %w", err)
	}
	if cq.getFolderViewThumbnailBlobDataByPathStmt, err = db.PrepareContext(ctx, getFolderViewThumbnailBlobDataByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetFolderViewThumbnailBlobDataByPath: %w", err)
	}
	if cq.getPreloadRoutesByFolderIDStmt, err = db.PrepareContext(ctx, getPreloadRoutesByFolderID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPreloadRoutesByFolderID: %w", err)
	}
	if cq.getThumbnailBlobDataByIDStmt, err = db.PrepareContext(ctx, getThumbnailBlobDataByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetThumbnailBlobDataByID: %w", err)
	}
	if cq.upsertThumbnailBlobStmt, err = db.PrepareContext(ctx, upsertThumbnailBlob); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertThumbnailBlob: %w", err)
	}

	ct_prepares.Add(1)
	slog.Debug("Prepared CustomQueries", "total_prepares", ct_prepares.Load())
	return cq, nil
}

// Close closes all prepared custom statements and delegates to the embedded Queries.Close().
func (cq *CustomQueries) Close() error {
	var errs []error

	if cq.getFileViewRowsByFolderIDStmt != nil {
		if err := cq.getFileViewRowsByFolderIDStmt.Close(); err != nil {
			errs = append(errs, fmt.Errorf("error closing getFileViewRowsByFolderIDStmt: %w", err))
		}
	}
	if cq.getFileViewRowsByFolderPathStmt != nil {
		if err := cq.getFileViewRowsByFolderPathStmt.Close(); err != nil {
			errs = append(errs, fmt.Errorf("error closing getFileViewRowsByFolderPathStmt: %w", err))
		}
	}
	if cq.getFolderViewThumbnailBlobDataByPathStmt != nil {
		if err := cq.getFolderViewThumbnailBlobDataByPathStmt.Close(); err != nil {
			errs = append(errs, fmt.Errorf("error closing getFolderViewThumbnailBlobDataByPathStmt: %w", err))
		}
	}
	if cq.getPreloadRoutesByFolderIDStmt != nil {
		if err := cq.getPreloadRoutesByFolderIDStmt.Close(); err != nil {
			errs = append(errs, fmt.Errorf("error closing getPreloadRoutesByFolderIDStmt: %w", err))
		}
	}
	if cq.getThumbnailBlobDataByIDStmt != nil {
		if err := cq.getThumbnailBlobDataByIDStmt.Close(); err != nil {
			errs = append(errs, fmt.Errorf("error closing getThumbnailBlobDataByIDStmt: %w", err))
		}
	}
	if cq.upsertThumbnailBlobStmt != nil {
		if err := cq.upsertThumbnailBlobStmt.Close(); err != nil {
			errs = append(errs, fmt.Errorf("error closing upsertThumbnailBlobStmt: %w", err))
		}
	}

	// Close the embedded Queries (which closes all its prepared statements).
	if qErr := cq.Queries.Close(); qErr != nil {
		errs = append(errs, fmt.Errorf("error closing embedded Queries: %w", qErr))
	}

	if len(errs) > 0 {
		for i, err := range errs {
			slog.Error("close error", "err", err, "index", i)
		}
		return errs[0]
	}
	return nil
}

// ============================================================================
// Custom Query SQL and Methods
// ============================================================================

const getFileViewRowsByFolderID = `-- name: GetFileViewRowsByFolderID :many
SELECT id, folder_id, folder_path, path, filename, size_bytes, md5, mime_type
     , width, height, created_at, updated_at 
  FROM file_view
 WHERE folder_id = ?
 ORDER BY filename`

// GetFileViewRowsByFolderID retrieves all files in a folder by folder ID.
func (cq *CustomQueries) GetFileViewRowsByFolderID(ctx context.Context, folderID int64) (*sql.Rows, error) {
	return cq.query(ctx, cq.getFileViewRowsByFolderIDStmt, getFileViewRowsByFolderID, folderID)
}

const getFileViewRowsByFolderPath = `-- name: GetFileViewRowsByFolderPath :many
SELECT id, folder_id, folder_path, path, filename, size_bytes, md5, mime_type
     , width, height, created_at, updated_at 
  FROM file_view
 WHERE folder_path = ?
 ORDER BY filename`

// GetFileViewRowsByFolderPath retrieves all files in a folder by folder path.
func (cq *CustomQueries) GetFileViewRowsByFolderPath(ctx context.Context, folderPath string) (*sql.Rows, error) {
	return cq.query(ctx, cq.getFileViewRowsByFolderPathStmt, getFileViewRowsByFolderPath, folderPath)
}

const getFolderViewThumbnailBlobDataByPath = `-- name: GetFolderViewThumbnailBlobDataByPath :one 
SELECT tb.data
  FROM folder_paths fp
       INNER JOIN folders f
               ON fp.id = f.path_id
       INNER JOIN thumbs.thumbnail_blobs tb 
               ON f.tile_id = tb.thumbnail_id
 WHERE fp.path = ?`

// GetFolderViewThumbnailBlobDataByPath retrieves the thumbnail blob for a folder's
// tile image directly via the folder path. This query joins the main DB with the
// thumbnail blob store.
func (cq *CustomQueries) GetFolderViewThumbnailBlobDataByPath(ctx context.Context, path string) ([]byte, error) {
	row := cq.queryRow(ctx, cq.getFolderViewThumbnailBlobDataByPathStmt, getFolderViewThumbnailBlobDataByPath, path)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getPreloadRoutesByFolderID = `-- name: GetPreloadRoutesByFolderID :many
WITH cte_cache_map AS (
    SELECT 'folder' AS cache_type, '/gallery/' AS cache_entry
    UNION ALL 
    SELECT 'folder' AS cache_type, '/info/folder/' AS cache_entry
    UNION ALL 
    SELECT 'file' AS cache_type, '/info/image/' AS cache_entry
    UNION ALL 
    SELECT 'file' AS cache_type, '/lightbox/' AS cache_entry
)
, cte_folders as (
    SELECT CASE WHEN f.parent_id IS NULL THEN 1 ELSE f.parent_id END AS parent_id, f.id AS folder_id, b.cache_entry || f.id as route 
      FROM folders f 
           INNER JOIN folders a 
                   ON f.parent_id = a.id 
           INNER JOIN cte_cache_map b 
                   ON b.cache_type = 'folder'
    UNION ALL 
    SELECT 1 AS parent_id, f.id AS folder_id, b.cache_entry || f.id as route 
      FROM folders f 
           CROSS JOIN cte_cache_map b 
                   ON b.cache_type = 'folder'
     WHERE f.parent_id is null 
)
, cte_files AS (
    SELECT CASE WHEN a.parent_id IS NULL THEN 1 ELSE a.parent_id END AS parent_id, f.folder_id, b.cache_entry || f.id as route
      FROM files f 
           INNER JOIN folders a 
                   ON f.folder_id = a.id 
           INNER JOIN cte_cache_map b 
                   ON b.cache_type = 'file'
)
, u AS (
    SELECT *
      FROM cte_folders
    UNION ALL
    SELECT *
      FROM cte_files
)
SELECT route 
  FROM u 
 WHERE ? IN (parent_id, folder_id)`

// GetPreloadRoutesByFolderID retrieves all preload routes for subfolders and files
// under the specified folder ID.
func (cq *CustomQueries) GetPreloadRoutesByFolderID(ctx context.Context, parent_id sql.NullInt64) (*sql.Rows, error) {
	return cq.query(ctx, cq.getPreloadRoutesByFolderIDStmt, getPreloadRoutesByFolderID, parent_id)
}

const getThumbnailBlobDataByID = `-- name: GetThumbnailBlobDataByID :one
SELECT data
  FROM thumbs.thumbnail_blobs 
 WHERE thumbnail_id = ?`

// GetThumbnailBlobDataByID retrieves thumbnail blob data by thumbnail ID.
// This method is now on CustomQueries to support the separate blob database.
func (cq *CustomQueries) GetThumbnailBlobDataByID(ctx context.Context, thumbnailID int64) ([]byte, error) {
	row := cq.queryRow(ctx, cq.getThumbnailBlobDataByIDStmt, getThumbnailBlobDataByID, thumbnailID)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const upsertThumbnailBlob = `-- name: UpsertThumbnailBlob :exec
INSERT INTO thumbs.thumbnail_blobs (thumbnail_id, data)
VALUES (?, ?)
    ON CONFLICT(thumbnail_id) 
    DO UPDATE SET data = excluded.data
            WHERE data IS NOT excluded.data`

// UpsertThumbnailBlobParams are the parameters for upserting a thumbnail blob.
type UpsertThumbnailBlobParams struct {
	ThumbnailID int64
	Data        []byte
}

// UpsertThumbnailBlob inserts or updates thumbnail blob data by thumbnail ID.
// This method is now on CustomQueries to support the separate blob database.
func (cq *CustomQueries) UpsertThumbnailBlob(ctx context.Context, arg UpsertThumbnailBlobParams) error {
	_, err := cq.exec(ctx, cq.upsertThumbnailBlobStmt, upsertThumbnailBlob, arg.ThumbnailID, arg.Data)
	return err
}

// WithTx returns a new CustomQueries instance with the provided transaction,
// allowing custom queries to be executed within a transaction. All prepared
// statements are propagated to the transactional instance.
func (cq *CustomQueries) WithTx(tx *sql.Tx) *CustomQueries {
	return &CustomQueries{
		Queries:                                  cq.Queries.WithTx(tx),
		getFileViewRowsByFolderIDStmt:            cq.getFileViewRowsByFolderIDStmt,
		getFileViewRowsByFolderPathStmt:          cq.getFileViewRowsByFolderPathStmt,
		getFolderViewThumbnailBlobDataByPathStmt: cq.getFolderViewThumbnailBlobDataByPathStmt,
		getPreloadRoutesByFolderIDStmt:           cq.getPreloadRoutesByFolderIDStmt,
		getThumbnailBlobDataByIDStmt:             cq.getThumbnailBlobDataByIDStmt,
		upsertThumbnailBlobStmt:                  cq.upsertThumbnailBlobStmt,
	}
}
