// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gallerydb

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.clearHttpCacheStmt, err = db.PrepareContext(ctx, clearHttpCache); err != nil {
		return nil, fmt.Errorf("error preparing query ClearHttpCache: %w", err)
	}
	if q.clearLoginAttemptsStmt, err = db.PrepareContext(ctx, clearLoginAttempts); err != nil {
		return nil, fmt.Errorf("error preparing query ClearLoginAttempts: %w", err)
	}
	if q.configKeyExistsStmt, err = db.PrepareContext(ctx, configKeyExists); err != nil {
		return nil, fmt.Errorf("error preparing query ConfigKeyExists: %w", err)
	}
	if q.countHttpCacheEntriesStmt, err = db.PrepareContext(ctx, countHttpCacheEntries); err != nil {
		return nil, fmt.Errorf("error preparing query CountHttpCacheEntries: %w", err)
	}
	if q.deleteHttpCacheByIDStmt, err = db.PrepareContext(ctx, deleteHttpCacheByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteHttpCacheByID: %w", err)
	}
	if q.deleteHttpCacheByKeyStmt, err = db.PrepareContext(ctx, deleteHttpCacheByKey); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteHttpCacheByKey: %w", err)
	}
	if q.deleteHttpCacheExpiredStmt, err = db.PrepareContext(ctx, deleteHttpCacheExpired); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteHttpCacheExpired: %w", err)
	}
	if q.deleteIPTCStmt, err = db.PrepareContext(ctx, deleteIPTC); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteIPTC: %w", err)
	}
	if q.deleteIPTCKeywordStmt, err = db.PrepareContext(ctx, deleteIPTCKeyword); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteIPTCKeyword: %w", err)
	}
	if q.deleteInvalidFileByPathStmt, err = db.PrepareContext(ctx, deleteInvalidFileByPath); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteInvalidFileByPath: %w", err)
	}
	if q.deleteXMPPropertyStmt, err = db.PrepareContext(ctx, deleteXMPProperty); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteXMPProperty: %w", err)
	}
	if q.deleteXMPRawStmt, err = db.PrepareContext(ctx, deleteXMPRaw); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteXMPRaw: %w", err)
	}
	if q.getConfigValueByKeyStmt, err = db.PrepareContext(ctx, getConfigValueByKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetConfigValueByKey: %w", err)
	}
	if q.getConfigsStmt, err = db.PrepareContext(ctx, getConfigs); err != nil {
		return nil, fmt.Errorf("error preparing query GetConfigs: %w", err)
	}
	if q.getExifByFileStmt, err = db.PrepareContext(ctx, getExifByFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetExifByFile: %w", err)
	}
	if q.getFileByPathStmt, err = db.PrepareContext(ctx, getFileByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileByPath: %w", err)
	}
	if q.getFileCountAndTimestampsStmt, err = db.PrepareContext(ctx, getFileCountAndTimestamps); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileCountAndTimestamps: %w", err)
	}
	if q.getFileFolderIndexByIDStmt, err = db.PrepareContext(ctx, getFileFolderIndexByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileFolderIndexByID: %w", err)
	}
	if q.getFileSizeSumStmt, err = db.PrepareContext(ctx, getFileSizeSum); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileSizeSum: %w", err)
	}
	if q.getFileViewByIDStmt, err = db.PrepareContext(ctx, getFileViewByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileViewByID: %w", err)
	}
	if q.getFolderByIDStmt, err = db.PrepareContext(ctx, getFolderByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetFolderByID: %w", err)
	}
	if q.getFolderByPathStmt, err = db.PrepareContext(ctx, getFolderByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetFolderByPath: %w", err)
	}
	if q.getFolderCountStmt, err = db.PrepareContext(ctx, getFolderCount); err != nil {
		return nil, fmt.Errorf("error preparing query GetFolderCount: %w", err)
	}
	if q.getFolderIDByPathStmt, err = db.PrepareContext(ctx, getFolderIDByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetFolderIDByPath: %w", err)
	}
	if q.getFolderInfoCountsByIDStmt, err = db.PrepareContext(ctx, getFolderInfoCountsByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetFolderInfoCountsByID: %w", err)
	}
	if q.getFolderTileExistsViewByPathStmt, err = db.PrepareContext(ctx, getFolderTileExistsViewByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetFolderTileExistsViewByPath: %w", err)
	}
	if q.getFolderViewByIDStmt, err = db.PrepareContext(ctx, getFolderViewByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetFolderViewByID: %w", err)
	}
	if q.getGalleryFileThumbRowsByFolderIDStmt, err = db.PrepareContext(ctx, getGalleryFileThumbRowsByFolderID); err != nil {
		return nil, fmt.Errorf("error preparing query GetGalleryFileThumbRowsByFolderID: %w", err)
	}
	if q.getGalleryFolderThumbRowsByParentIDStmt, err = db.PrepareContext(ctx, getGalleryFolderThumbRowsByParentID); err != nil {
		return nil, fmt.Errorf("error preparing query GetGalleryFolderThumbRowsByParentID: %w", err)
	}
	if q.getHttpCacheByKeyStmt, err = db.PrepareContext(ctx, getHttpCacheByKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetHttpCacheByKey: %w", err)
	}
	if q.getHttpCacheOldestCreatedStmt, err = db.PrepareContext(ctx, getHttpCacheOldestCreated); err != nil {
		return nil, fmt.Errorf("error preparing query GetHttpCacheOldestCreated: %w", err)
	}
	if q.getHttpCacheSizeBytesStmt, err = db.PrepareContext(ctx, getHttpCacheSizeBytes); err != nil {
		return nil, fmt.Errorf("error preparing query GetHttpCacheSizeBytes: %w", err)
	}
	if q.getIPTCByFileStmt, err = db.PrepareContext(ctx, getIPTCByFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetIPTCByFile: %w", err)
	}
	if q.getIPTCKeywordsStmt, err = db.PrepareContext(ctx, getIPTCKeywords); err != nil {
		return nil, fmt.Errorf("error preparing query GetIPTCKeywords: %w", err)
	}
	if q.getInvalidFileByPathStmt, err = db.PrepareContext(ctx, getInvalidFileByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetInvalidFileByPath: %w", err)
	}
	if q.getLightboxNavByFileIDStmt, err = db.PrepareContext(ctx, getLightboxNavByFileID); err != nil {
		return nil, fmt.Errorf("error preparing query GetLightboxNavByFileID: %w", err)
	}
	if q.getLoginAttemptStmt, err = db.PrepareContext(ctx, getLoginAttempt); err != nil {
		return nil, fmt.Errorf("error preparing query GetLoginAttempt: %w", err)
	}
	if q.getModuleStateStmt, err = db.PrepareContext(ctx, getModuleState); err != nil {
		return nil, fmt.Errorf("error preparing query GetModuleState: %w", err)
	}
	if q.getThumbnailExistsViewByIDStmt, err = db.PrepareContext(ctx, getThumbnailExistsViewByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetThumbnailExistsViewByID: %w", err)
	}
	if q.getThumbnailsByFileIDStmt, err = db.PrepareContext(ctx, getThumbnailsByFileID); err != nil {
		return nil, fmt.Errorf("error preparing query GetThumbnailsByFileID: %w", err)
	}
	if q.getXMPPropertiesByFileStmt, err = db.PrepareContext(ctx, getXMPPropertiesByFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetXMPPropertiesByFile: %w", err)
	}
	if q.getXMPRawStmt, err = db.PrepareContext(ctx, getXMPRaw); err != nil {
		return nil, fmt.Errorf("error preparing query GetXMPRaw: %w", err)
	}
	if q.httpCacheExistsByKeyStmt, err = db.PrepareContext(ctx, httpCacheExistsByKey); err != nil {
		return nil, fmt.Errorf("error preparing query HttpCacheExistsByKey: %w", err)
	}
	if q.insertConfigIfNotExistsStmt, err = db.PrepareContext(ctx, insertConfigIfNotExists); err != nil {
		return nil, fmt.Errorf("error preparing query InsertConfigIfNotExists: %w", err)
	}
	if q.insertIPTCKeywordStmt, err = db.PrepareContext(ctx, insertIPTCKeyword); err != nil {
		return nil, fmt.Errorf("error preparing query InsertIPTCKeyword: %w", err)
	}
	if q.setModuleStateStmt, err = db.PrepareContext(ctx, setModuleState); err != nil {
		return nil, fmt.Errorf("error preparing query SetModuleState: %w", err)
	}
	if q.setModuleStatePayloadStmt, err = db.PrepareContext(ctx, setModuleStatePayload); err != nil {
		return nil, fmt.Errorf("error preparing query SetModuleStatePayload: %w", err)
	}
	if q.unlockAccountStmt, err = db.PrepareContext(ctx, unlockAccount); err != nil {
		return nil, fmt.Errorf("error preparing query UnlockAccount: %w", err)
	}
	if q.updateFolderTileIdStmt, err = db.PrepareContext(ctx, updateFolderTileId); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateFolderTileId: %w", err)
	}
	if q.upsertConfigValueOnlyStmt, err = db.PrepareContext(ctx, upsertConfigValueOnly); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertConfigValueOnly: %w", err)
	}
	if q.upsertExifStmt, err = db.PrepareContext(ctx, upsertExif); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertExif: %w", err)
	}
	if q.upsertFilePathReturningIDStmt, err = db.PrepareContext(ctx, upsertFilePathReturningID); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertFilePathReturningID: %w", err)
	}
	if q.upsertFileReturningFileStmt, err = db.PrepareContext(ctx, upsertFileReturningFile); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertFileReturningFile: %w", err)
	}
	if q.upsertFolderPathReturningIDStmt, err = db.PrepareContext(ctx, upsertFolderPathReturningID); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertFolderPathReturningID: %w", err)
	}
	if q.upsertFolderReturningFolderStmt, err = db.PrepareContext(ctx, upsertFolderReturningFolder); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertFolderReturningFolder: %w", err)
	}
	if q.upsertHttpCacheStmt, err = db.PrepareContext(ctx, upsertHttpCache); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertHttpCache: %w", err)
	}
	if q.upsertIPTCStmt, err = db.PrepareContext(ctx, upsertIPTC); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertIPTC: %w", err)
	}
	if q.upsertInvalidFileStmt, err = db.PrepareContext(ctx, upsertInvalidFile); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertInvalidFile: %w", err)
	}
	if q.upsertLoginAttemptStmt, err = db.PrepareContext(ctx, upsertLoginAttempt); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertLoginAttempt: %w", err)
	}
	if q.upsertThumbnailReturningIDStmt, err = db.PrepareContext(ctx, upsertThumbnailReturningID); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertThumbnailReturningID: %w", err)
	}
	if q.upsertXMPPropertyStmt, err = db.PrepareContext(ctx, upsertXMPProperty); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertXMPProperty: %w", err)
	}
	if q.upsertXMPRawStmt, err = db.PrepareContext(ctx, upsertXMPRaw); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertXMPRaw: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.clearHttpCacheStmt != nil {
		if cerr := q.clearHttpCacheStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearHttpCacheStmt: %w", cerr)
		}
	}
	if q.clearLoginAttemptsStmt != nil {
		if cerr := q.clearLoginAttemptsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearLoginAttemptsStmt: %w", cerr)
		}
	}
	if q.configKeyExistsStmt != nil {
		if cerr := q.configKeyExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing configKeyExistsStmt: %w", cerr)
		}
	}
	if q.countHttpCacheEntriesStmt != nil {
		if cerr := q.countHttpCacheEntriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countHttpCacheEntriesStmt: %w", cerr)
		}
	}
	if q.deleteHttpCacheByIDStmt != nil {
		if cerr := q.deleteHttpCacheByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteHttpCacheByIDStmt: %w", cerr)
		}
	}
	if q.deleteHttpCacheByKeyStmt != nil {
		if cerr := q.deleteHttpCacheByKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteHttpCacheByKeyStmt: %w", cerr)
		}
	}
	if q.deleteHttpCacheExpiredStmt != nil {
		if cerr := q.deleteHttpCacheExpiredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteHttpCacheExpiredStmt: %w", cerr)
		}
	}
	if q.deleteIPTCStmt != nil {
		if cerr := q.deleteIPTCStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteIPTCStmt: %w", cerr)
		}
	}
	if q.deleteIPTCKeywordStmt != nil {
		if cerr := q.deleteIPTCKeywordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteIPTCKeywordStmt: %w", cerr)
		}
	}
	if q.deleteInvalidFileByPathStmt != nil {
		if cerr := q.deleteInvalidFileByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteInvalidFileByPathStmt: %w", cerr)
		}
	}
	if q.deleteXMPPropertyStmt != nil {
		if cerr := q.deleteXMPPropertyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteXMPPropertyStmt: %w", cerr)
		}
	}
	if q.deleteXMPRawStmt != nil {
		if cerr := q.deleteXMPRawStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteXMPRawStmt: %w", cerr)
		}
	}
	if q.getConfigValueByKeyStmt != nil {
		if cerr := q.getConfigValueByKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getConfigValueByKeyStmt: %w", cerr)
		}
	}
	if q.getConfigsStmt != nil {
		if cerr := q.getConfigsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getConfigsStmt: %w", cerr)
		}
	}
	if q.getExifByFileStmt != nil {
		if cerr := q.getExifByFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getExifByFileStmt: %w", cerr)
		}
	}
	if q.getFileByPathStmt != nil {
		if cerr := q.getFileByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileByPathStmt: %w", cerr)
		}
	}
	if q.getFileCountAndTimestampsStmt != nil {
		if cerr := q.getFileCountAndTimestampsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileCountAndTimestampsStmt: %w", cerr)
		}
	}
	if q.getFileFolderIndexByIDStmt != nil {
		if cerr := q.getFileFolderIndexByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileFolderIndexByIDStmt: %w", cerr)
		}
	}
	if q.getFileSizeSumStmt != nil {
		if cerr := q.getFileSizeSumStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileSizeSumStmt: %w", cerr)
		}
	}
	if q.getFileViewByIDStmt != nil {
		if cerr := q.getFileViewByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileViewByIDStmt: %w", cerr)
		}
	}
	if q.getFolderByIDStmt != nil {
		if cerr := q.getFolderByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFolderByIDStmt: %w", cerr)
		}
	}
	if q.getFolderByPathStmt != nil {
		if cerr := q.getFolderByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFolderByPathStmt: %w", cerr)
		}
	}
	if q.getFolderCountStmt != nil {
		if cerr := q.getFolderCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFolderCountStmt: %w", cerr)
		}
	}
	if q.getFolderIDByPathStmt != nil {
		if cerr := q.getFolderIDByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFolderIDByPathStmt: %w", cerr)
		}
	}
	if q.getFolderInfoCountsByIDStmt != nil {
		if cerr := q.getFolderInfoCountsByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFolderInfoCountsByIDStmt: %w", cerr)
		}
	}
	if q.getFolderTileExistsViewByPathStmt != nil {
		if cerr := q.getFolderTileExistsViewByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFolderTileExistsViewByPathStmt: %w", cerr)
		}
	}
	if q.getFolderViewByIDStmt != nil {
		if cerr := q.getFolderViewByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFolderViewByIDStmt: %w", cerr)
		}
	}
	if q.getGalleryFileThumbRowsByFolderIDStmt != nil {
		if cerr := q.getGalleryFileThumbRowsByFolderIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGalleryFileThumbRowsByFolderIDStmt: %w", cerr)
		}
	}
	if q.getGalleryFolderThumbRowsByParentIDStmt != nil {
		if cerr := q.getGalleryFolderThumbRowsByParentIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGalleryFolderThumbRowsByParentIDStmt: %w", cerr)
		}
	}
	if q.getHttpCacheByKeyStmt != nil {
		if cerr := q.getHttpCacheByKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHttpCacheByKeyStmt: %w", cerr)
		}
	}
	if q.getHttpCacheOldestCreatedStmt != nil {
		if cerr := q.getHttpCacheOldestCreatedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHttpCacheOldestCreatedStmt: %w", cerr)
		}
	}
	if q.getHttpCacheSizeBytesStmt != nil {
		if cerr := q.getHttpCacheSizeBytesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHttpCacheSizeBytesStmt: %w", cerr)
		}
	}
	if q.getIPTCByFileStmt != nil {
		if cerr := q.getIPTCByFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIPTCByFileStmt: %w", cerr)
		}
	}
	if q.getIPTCKeywordsStmt != nil {
		if cerr := q.getIPTCKeywordsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIPTCKeywordsStmt: %w", cerr)
		}
	}
	if q.getInvalidFileByPathStmt != nil {
		if cerr := q.getInvalidFileByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getInvalidFileByPathStmt: %w", cerr)
		}
	}
	if q.getLightboxNavByFileIDStmt != nil {
		if cerr := q.getLightboxNavByFileIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLightboxNavByFileIDStmt: %w", cerr)
		}
	}
	if q.getLoginAttemptStmt != nil {
		if cerr := q.getLoginAttemptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLoginAttemptStmt: %w", cerr)
		}
	}
	if q.getModuleStateStmt != nil {
		if cerr := q.getModuleStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getModuleStateStmt: %w", cerr)
		}
	}
	if q.getThumbnailExistsViewByIDStmt != nil {
		if cerr := q.getThumbnailExistsViewByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getThumbnailExistsViewByIDStmt: %w", cerr)
		}
	}
	if q.getThumbnailsByFileIDStmt != nil {
		if cerr := q.getThumbnailsByFileIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getThumbnailsByFileIDStmt: %w", cerr)
		}
	}
	if q.getXMPPropertiesByFileStmt != nil {
		if cerr := q.getXMPPropertiesByFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getXMPPropertiesByFileStmt: %w", cerr)
		}
	}
	if q.getXMPRawStmt != nil {
		if cerr := q.getXMPRawStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getXMPRawStmt: %w", cerr)
		}
	}
	if q.httpCacheExistsByKeyStmt != nil {
		if cerr := q.httpCacheExistsByKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing httpCacheExistsByKeyStmt: %w", cerr)
		}
	}
	if q.insertConfigIfNotExistsStmt != nil {
		if cerr := q.insertConfigIfNotExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertConfigIfNotExistsStmt: %w", cerr)
		}
	}
	if q.insertIPTCKeywordStmt != nil {
		if cerr := q.insertIPTCKeywordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertIPTCKeywordStmt: %w", cerr)
		}
	}
	if q.setModuleStateStmt != nil {
		if cerr := q.setModuleStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setModuleStateStmt: %w", cerr)
		}
	}
	if q.setModuleStatePayloadStmt != nil {
		if cerr := q.setModuleStatePayloadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setModuleStatePayloadStmt: %w", cerr)
		}
	}
	if q.unlockAccountStmt != nil {
		if cerr := q.unlockAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing unlockAccountStmt: %w", cerr)
		}
	}
	if q.updateFolderTileIdStmt != nil {
		if cerr := q.updateFolderTileIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateFolderTileIdStmt: %w", cerr)
		}
	}
	if q.upsertConfigValueOnlyStmt != nil {
		if cerr := q.upsertConfigValueOnlyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertConfigValueOnlyStmt: %w", cerr)
		}
	}
	if q.upsertExifStmt != nil {
		if cerr := q.upsertExifStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertExifStmt: %w", cerr)
		}
	}
	if q.upsertFilePathReturningIDStmt != nil {
		if cerr := q.upsertFilePathReturningIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertFilePathReturningIDStmt: %w", cerr)
		}
	}
	if q.upsertFileReturningFileStmt != nil {
		if cerr := q.upsertFileReturningFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertFileReturningFileStmt: %w", cerr)
		}
	}
	if q.upsertFolderPathReturningIDStmt != nil {
		if cerr := q.upsertFolderPathReturningIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertFolderPathReturningIDStmt: %w", cerr)
		}
	}
	if q.upsertFolderReturningFolderStmt != nil {
		if cerr := q.upsertFolderReturningFolderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertFolderReturningFolderStmt: %w", cerr)
		}
	}
	if q.upsertHttpCacheStmt != nil {
		if cerr := q.upsertHttpCacheStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertHttpCacheStmt: %w", cerr)
		}
	}
	if q.upsertIPTCStmt != nil {
		if cerr := q.upsertIPTCStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertIPTCStmt: %w", cerr)
		}
	}
	if q.upsertInvalidFileStmt != nil {
		if cerr := q.upsertInvalidFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertInvalidFileStmt: %w", cerr)
		}
	}
	if q.upsertLoginAttemptStmt != nil {
		if cerr := q.upsertLoginAttemptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertLoginAttemptStmt: %w", cerr)
		}
	}
	if q.upsertThumbnailReturningIDStmt != nil {
		if cerr := q.upsertThumbnailReturningIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertThumbnailReturningIDStmt: %w", cerr)
		}
	}
	if q.upsertXMPPropertyStmt != nil {
		if cerr := q.upsertXMPPropertyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertXMPPropertyStmt: %w", cerr)
		}
	}
	if q.upsertXMPRawStmt != nil {
		if cerr := q.upsertXMPRawStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertXMPRawStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                      DBTX
	tx                                      *sql.Tx
	clearHttpCacheStmt                      *sql.Stmt
	clearLoginAttemptsStmt                  *sql.Stmt
	configKeyExistsStmt                     *sql.Stmt
	countHttpCacheEntriesStmt               *sql.Stmt
	deleteHttpCacheByIDStmt                 *sql.Stmt
	deleteHttpCacheByKeyStmt                *sql.Stmt
	deleteHttpCacheExpiredStmt              *sql.Stmt
	deleteIPTCStmt                          *sql.Stmt
	deleteIPTCKeywordStmt                   *sql.Stmt
	deleteInvalidFileByPathStmt             *sql.Stmt
	deleteXMPPropertyStmt                   *sql.Stmt
	deleteXMPRawStmt                        *sql.Stmt
	getConfigValueByKeyStmt                 *sql.Stmt
	getConfigsStmt                          *sql.Stmt
	getExifByFileStmt                       *sql.Stmt
	getFileByPathStmt                       *sql.Stmt
	getFileCountAndTimestampsStmt           *sql.Stmt
	getFileFolderIndexByIDStmt              *sql.Stmt
	getFileSizeSumStmt                      *sql.Stmt
	getFileViewByIDStmt                     *sql.Stmt
	getFolderByIDStmt                       *sql.Stmt
	getFolderByPathStmt                     *sql.Stmt
	getFolderCountStmt                      *sql.Stmt
	getFolderIDByPathStmt                   *sql.Stmt
	getFolderInfoCountsByIDStmt             *sql.Stmt
	getFolderTileExistsViewByPathStmt       *sql.Stmt
	getFolderViewByIDStmt                   *sql.Stmt
	getGalleryFileThumbRowsByFolderIDStmt   *sql.Stmt
	getGalleryFolderThumbRowsByParentIDStmt *sql.Stmt
	getHttpCacheByKeyStmt                   *sql.Stmt
	getHttpCacheOldestCreatedStmt           *sql.Stmt
	getHttpCacheSizeBytesStmt               *sql.Stmt
	getIPTCByFileStmt                       *sql.Stmt
	getIPTCKeywordsStmt                     *sql.Stmt
	getInvalidFileByPathStmt                *sql.Stmt
	getLightboxNavByFileIDStmt              *sql.Stmt
	getLoginAttemptStmt                     *sql.Stmt
	getModuleStateStmt                      *sql.Stmt
	getThumbnailExistsViewByIDStmt          *sql.Stmt
	getThumbnailsByFileIDStmt               *sql.Stmt
	getXMPPropertiesByFileStmt              *sql.Stmt
	getXMPRawStmt                           *sql.Stmt
	httpCacheExistsByKeyStmt                *sql.Stmt
	insertConfigIfNotExistsStmt             *sql.Stmt
	insertIPTCKeywordStmt                   *sql.Stmt
	setModuleStateStmt                      *sql.Stmt
	setModuleStatePayloadStmt               *sql.Stmt
	unlockAccountStmt                       *sql.Stmt
	updateFolderTileIdStmt                  *sql.Stmt
	upsertConfigValueOnlyStmt               *sql.Stmt
	upsertExifStmt                          *sql.Stmt
	upsertFilePathReturningIDStmt           *sql.Stmt
	upsertFileReturningFileStmt             *sql.Stmt
	upsertFolderPathReturningIDStmt         *sql.Stmt
	upsertFolderReturningFolderStmt         *sql.Stmt
	upsertHttpCacheStmt                     *sql.Stmt
	upsertIPTCStmt                          *sql.Stmt
	upsertInvalidFileStmt                   *sql.Stmt
	upsertLoginAttemptStmt                  *sql.Stmt
	upsertThumbnailReturningIDStmt          *sql.Stmt
	upsertXMPPropertyStmt                   *sql.Stmt
	upsertXMPRawStmt                        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                      tx,
		tx:                                      tx,
		clearHttpCacheStmt:                      q.clearHttpCacheStmt,
		clearLoginAttemptsStmt:                  q.clearLoginAttemptsStmt,
		configKeyExistsStmt:                     q.configKeyExistsStmt,
		countHttpCacheEntriesStmt:               q.countHttpCacheEntriesStmt,
		deleteHttpCacheByIDStmt:                 q.deleteHttpCacheByIDStmt,
		deleteHttpCacheByKeyStmt:                q.deleteHttpCacheByKeyStmt,
		deleteHttpCacheExpiredStmt:              q.deleteHttpCacheExpiredStmt,
		deleteIPTCStmt:                          q.deleteIPTCStmt,
		deleteIPTCKeywordStmt:                   q.deleteIPTCKeywordStmt,
		deleteInvalidFileByPathStmt:             q.deleteInvalidFileByPathStmt,
		deleteXMPPropertyStmt:                   q.deleteXMPPropertyStmt,
		deleteXMPRawStmt:                        q.deleteXMPRawStmt,
		getConfigValueByKeyStmt:                 q.getConfigValueByKeyStmt,
		getConfigsStmt:                          q.getConfigsStmt,
		getExifByFileStmt:                       q.getExifByFileStmt,
		getFileByPathStmt:                       q.getFileByPathStmt,
		getFileCountAndTimestampsStmt:           q.getFileCountAndTimestampsStmt,
		getFileFolderIndexByIDStmt:              q.getFileFolderIndexByIDStmt,
		getFileSizeSumStmt:                      q.getFileSizeSumStmt,
		getFileViewByIDStmt:                     q.getFileViewByIDStmt,
		getFolderByIDStmt:                       q.getFolderByIDStmt,
		getFolderByPathStmt:                     q.getFolderByPathStmt,
		getFolderCountStmt:                      q.getFolderCountStmt,
		getFolderIDByPathStmt:                   q.getFolderIDByPathStmt,
		getFolderInfoCountsByIDStmt:             q.getFolderInfoCountsByIDStmt,
		getFolderTileExistsViewByPathStmt:       q.getFolderTileExistsViewByPathStmt,
		getFolderViewByIDStmt:                   q.getFolderViewByIDStmt,
		getGalleryFileThumbRowsByFolderIDStmt:   q.getGalleryFileThumbRowsByFolderIDStmt,
		getGalleryFolderThumbRowsByParentIDStmt: q.getGalleryFolderThumbRowsByParentIDStmt,
		getHttpCacheByKeyStmt:                   q.getHttpCacheByKeyStmt,
		getHttpCacheOldestCreatedStmt:           q.getHttpCacheOldestCreatedStmt,
		getHttpCacheSizeBytesStmt:               q.getHttpCacheSizeBytesStmt,
		getIPTCByFileStmt:                       q.getIPTCByFileStmt,
		getIPTCKeywordsStmt:                     q.getIPTCKeywordsStmt,
		getInvalidFileByPathStmt:                q.getInvalidFileByPathStmt,
		getLightboxNavByFileIDStmt:              q.getLightboxNavByFileIDStmt,
		getLoginAttemptStmt:                     q.getLoginAttemptStmt,
		getModuleStateStmt:                      q.getModuleStateStmt,
		getThumbnailExistsViewByIDStmt:          q.getThumbnailExistsViewByIDStmt,
		getThumbnailsByFileIDStmt:               q.getThumbnailsByFileIDStmt,
		getXMPPropertiesByFileStmt:              q.getXMPPropertiesByFileStmt,
		getXMPRawStmt:                           q.getXMPRawStmt,
		httpCacheExistsByKeyStmt:                q.httpCacheExistsByKeyStmt,
		insertConfigIfNotExistsStmt:             q.insertConfigIfNotExistsStmt,
		insertIPTCKeywordStmt:                   q.insertIPTCKeywordStmt,
		setModuleStateStmt:                      q.setModuleStateStmt,
		setModuleStatePayloadStmt:               q.setModuleStatePayloadStmt,
		unlockAccountStmt:                       q.unlockAccountStmt,
		updateFolderTileIdStmt:                  q.updateFolderTileIdStmt,
		upsertConfigValueOnlyStmt:               q.upsertConfigValueOnlyStmt,
		upsertExifStmt:                          q.upsertExifStmt,
		upsertFilePathReturningIDStmt:           q.upsertFilePathReturningIDStmt,
		upsertFileReturningFileStmt:             q.upsertFileReturningFileStmt,
		upsertFolderPathReturningIDStmt:         q.upsertFolderPathReturningIDStmt,
		upsertFolderReturningFolderStmt:         q.upsertFolderReturningFolderStmt,
		upsertHttpCacheStmt:                     q.upsertHttpCacheStmt,
		upsertIPTCStmt:                          q.upsertIPTCStmt,
		upsertInvalidFileStmt:                   q.upsertInvalidFileStmt,
		upsertLoginAttemptStmt:                  q.upsertLoginAttemptStmt,
		upsertThumbnailReturningIDStmt:          q.upsertThumbnailReturningIDStmt,
		upsertXMPPropertyStmt:                   q.upsertXMPPropertyStmt,
		upsertXMPRawStmt:                        q.upsertXMPRawStmt,
	}
}
