// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gallerydb

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

var (
	// prepareContextFn is a testable hook for DBTX.PrepareContext.
	prepareContextFn = func(ctx context.Context, db DBTX, query string) (*sql.Stmt, error) {
		return db.PrepareContext(ctx, query)
	}

	// stmtCloseFn is a testable hook for *sql.Stmt.Close.
	stmtCloseFn = func(s *sql.Stmt) error {
		return s.Close()
	}

	// rowsCloseFn is a testable hook for *sql.Rows.Close.
	rowsCloseFn = func(r *sql.Rows) error {
		return r.Close()
	}

	// rowsErrFn is a testable hook for *sql.Rows.Err.
	rowsErrFn = func(r *sql.Rows) error {
		return r.Err()
	}
)

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.clearHttpCacheStmt, err = prepareContextFn(ctx, db, clearHttpCache); err != nil {
		return nil, fmt.Errorf("error preparing query ClearHttpCache: %w", err)
	}
	if q.clearLoginAttemptsStmt, err = prepareContextFn(ctx, db, clearLoginAttempts); err != nil {
		return nil, fmt.Errorf("error preparing query ClearLoginAttempts: %w", err)
	}
	if q.configKeyExistsStmt, err = prepareContextFn(ctx, db, configKeyExists); err != nil {
		return nil, fmt.Errorf("error preparing query ConfigKeyExists: %w", err)
	}
	if q.countHttpCacheEntriesStmt, err = prepareContextFn(ctx, db, countHttpCacheEntries); err != nil {
		return nil, fmt.Errorf("error preparing query CountHttpCacheEntries: %w", err)
	}
	if q.deleteHttpCacheByIDStmt, err = prepareContextFn(ctx, db, deleteHttpCacheByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteHttpCacheByID: %w", err)
	}
	if q.deleteHttpCacheByKeyStmt, err = prepareContextFn(ctx, db, deleteHttpCacheByKey); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteHttpCacheByKey: %w", err)
	}
	if q.deleteHttpCacheExpiredStmt, err = prepareContextFn(ctx, db, deleteHttpCacheExpired); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteHttpCacheExpired: %w", err)
	}
	if q.deleteIPTCStmt, err = prepareContextFn(ctx, db, deleteIPTC); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteIPTC: %w", err)
	}
	if q.deleteIPTCKeywordStmt, err = prepareContextFn(ctx, db, deleteIPTCKeyword); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteIPTCKeyword: %w", err)
	}
	if q.deleteInvalidFileByPathStmt, err = prepareContextFn(ctx, db, deleteInvalidFileByPath); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteInvalidFileByPath: %w", err)
	}
	if q.deleteXMPPropertyStmt, err = prepareContextFn(ctx, db, deleteXMPProperty); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteXMPProperty: %w", err)
	}
	if q.deleteXMPRawStmt, err = prepareContextFn(ctx, db, deleteXMPRaw); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteXMPRaw: %w", err)
	}
	if q.getConfigValueByKeyStmt, err = prepareContextFn(ctx, db, getConfigValueByKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetConfigValueByKey: %w", err)
	}
	if q.getConfigsStmt, err = prepareContextFn(ctx, db, getConfigs); err != nil {
		return nil, fmt.Errorf("error preparing query GetConfigs: %w", err)
	}
	if q.getExifByFileStmt, err = prepareContextFn(ctx, db, getExifByFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetExifByFile: %w", err)
	}
	if q.getFileByPathStmt, err = prepareContextFn(ctx, db, getFileByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileByPath: %w", err)
	}
	if q.getFileViewByIDStmt, err = prepareContextFn(ctx, db, getFileViewByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileViewByID: %w", err)
	}
	if q.getFileViewsByFolderIDOrderByFileNameStmt, err = prepareContextFn(ctx, db, getFileViewsByFolderIDOrderByFileName); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileViewsByFolderIDOrderByFileName: %w", err)
	}
	if q.getFolderByIDStmt, err = prepareContextFn(ctx, db, getFolderByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetFolderByID: %w", err)
	}
	if q.getFolderByPathStmt, err = prepareContextFn(ctx, db, getFolderByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetFolderByPath: %w", err)
	}
	if q.getFolderIDByPathStmt, err = prepareContextFn(ctx, db, getFolderIDByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetFolderIDByPath: %w", err)
	}
	if q.getFolderTileExistsViewByPathStmt, err = prepareContextFn(ctx, db, getFolderTileExistsViewByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetFolderTileExistsViewByPath: %w", err)
	}
	if q.getFolderViewByIDStmt, err = prepareContextFn(ctx, db, getFolderViewByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetFolderViewByID: %w", err)
	}
	if q.getFoldersViewsByParentIDOrderByNameStmt, err = prepareContextFn(ctx, db, getFoldersViewsByParentIDOrderByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetFoldersViewsByParentIDOrderByName: %w", err)
	}
	if q.getGalleryStatisticsStmt, err = prepareContextFn(ctx, db, getGalleryStatistics); err != nil {
		return nil, fmt.Errorf("error preparing query GetGalleryStatistics: %w", err)
	}
	if q.getHttpCacheByKeyStmt, err = prepareContextFn(ctx, db, getHttpCacheByKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetHttpCacheByKey: %w", err)
	}
	if q.getHttpCacheOldestCreatedStmt, err = prepareContextFn(ctx, db, getHttpCacheOldestCreated); err != nil {
		return nil, fmt.Errorf("error preparing query GetHttpCacheOldestCreated: %w", err)
	}
	if q.getHttpCacheSizeBytesStmt, err = prepareContextFn(ctx, db, getHttpCacheSizeBytes); err != nil {
		return nil, fmt.Errorf("error preparing query GetHttpCacheSizeBytes: %w", err)
	}
	if q.getIPTCByFileStmt, err = prepareContextFn(ctx, db, getIPTCByFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetIPTCByFile: %w", err)
	}
	if q.getIPTCKeywordsStmt, err = prepareContextFn(ctx, db, getIPTCKeywords); err != nil {
		return nil, fmt.Errorf("error preparing query GetIPTCKeywords: %w", err)
	}
	if q.getInvalidFileByPathStmt, err = prepareContextFn(ctx, db, getInvalidFileByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetInvalidFileByPath: %w", err)
	}
	if q.getLoginAttemptStmt, err = prepareContextFn(ctx, db, getLoginAttempt); err != nil {
		return nil, fmt.Errorf("error preparing query GetLoginAttempt: %w", err)
	}
	if q.getModuleStateStmt, err = prepareContextFn(ctx, db, getModuleState); err != nil {
		return nil, fmt.Errorf("error preparing query GetModuleState: %w", err)
	}
	if q.getThumbnailExistsViewByIDStmt, err = prepareContextFn(ctx, db, getThumbnailExistsViewByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetThumbnailExistsViewByID: %w", err)
	}
	if q.getThumbnailsByFileIDStmt, err = prepareContextFn(ctx, db, getThumbnailsByFileID); err != nil {
		return nil, fmt.Errorf("error preparing query GetThumbnailsByFileID: %w", err)
	}
	if q.getXMPPropertiesByFileStmt, err = prepareContextFn(ctx, db, getXMPPropertiesByFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetXMPPropertiesByFile: %w", err)
	}
	if q.getXMPRawStmt, err = prepareContextFn(ctx, db, getXMPRaw); err != nil {
		return nil, fmt.Errorf("error preparing query GetXMPRaw: %w", err)
	}
	if q.httpCacheExistsByKeyStmt, err = prepareContextFn(ctx, db, httpCacheExistsByKey); err != nil {
		return nil, fmt.Errorf("error preparing query HttpCacheExistsByKey: %w", err)
	}
	if q.insertConfigIfNotExistsStmt, err = prepareContextFn(ctx, db, insertConfigIfNotExists); err != nil {
		return nil, fmt.Errorf("error preparing query InsertConfigIfNotExists: %w", err)
	}
	if q.insertIPTCKeywordStmt, err = prepareContextFn(ctx, db, insertIPTCKeyword); err != nil {
		return nil, fmt.Errorf("error preparing query InsertIPTCKeyword: %w", err)
	}
	if q.setModuleStateStmt, err = prepareContextFn(ctx, db, setModuleState); err != nil {
		return nil, fmt.Errorf("error preparing query SetModuleState: %w", err)
	}
	if q.unlockAccountStmt, err = prepareContextFn(ctx, db, unlockAccount); err != nil {
		return nil, fmt.Errorf("error preparing query UnlockAccount: %w", err)
	}
	if q.updateFolderTileIdStmt, err = prepareContextFn(ctx, db, updateFolderTileId); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateFolderTileId: %w", err)
	}
	if q.upsertConfigValueOnlyStmt, err = prepareContextFn(ctx, db, upsertConfigValueOnly); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertConfigValueOnly: %w", err)
	}
	if q.upsertExifStmt, err = prepareContextFn(ctx, db, upsertExif); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertExif: %w", err)
	}
	if q.upsertFilePathReturningIDStmt, err = prepareContextFn(ctx, db, upsertFilePathReturningID); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertFilePathReturningID: %w", err)
	}
	if q.upsertFileReturningFileStmt, err = prepareContextFn(ctx, db, upsertFileReturningFile); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertFileReturningFile: %w", err)
	}
	if q.upsertFolderPathReturningIDStmt, err = prepareContextFn(ctx, db, upsertFolderPathReturningID); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertFolderPathReturningID: %w", err)
	}
	if q.upsertFolderReturningFolderStmt, err = prepareContextFn(ctx, db, upsertFolderReturningFolder); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertFolderReturningFolder: %w", err)
	}
	if q.upsertHttpCacheStmt, err = prepareContextFn(ctx, db, upsertHttpCache); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertHttpCache: %w", err)
	}
	if q.upsertIPTCStmt, err = prepareContextFn(ctx, db, upsertIPTC); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertIPTC: %w", err)
	}
	if q.upsertInvalidFileStmt, err = prepareContextFn(ctx, db, upsertInvalidFile); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertInvalidFile: %w", err)
	}
	if q.upsertLoginAttemptStmt, err = prepareContextFn(ctx, db, upsertLoginAttempt); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertLoginAttempt: %w", err)
	}
	if q.upsertThumbnailReturningIDStmt, err = prepareContextFn(ctx, db, upsertThumbnailReturningID); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertThumbnailReturningID: %w", err)
	}
	if q.upsertXMPPropertyStmt, err = prepareContextFn(ctx, db, upsertXMPProperty); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertXMPProperty: %w", err)
	}
	if q.upsertXMPRawStmt, err = prepareContextFn(ctx, db, upsertXMPRaw); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertXMPRaw: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.clearHttpCacheStmt != nil {
		if cerr := stmtCloseFn(q.clearHttpCacheStmt); cerr != nil {
			err = fmt.Errorf("error closing clearHttpCacheStmt: %w", cerr)
		}
	}
	if q.clearLoginAttemptsStmt != nil {
		if cerr := stmtCloseFn(q.clearLoginAttemptsStmt); cerr != nil {
			err = fmt.Errorf("error closing clearLoginAttemptsStmt: %w", cerr)
		}
	}
	if q.configKeyExistsStmt != nil {
		if cerr := stmtCloseFn(q.configKeyExistsStmt); cerr != nil {
			err = fmt.Errorf("error closing configKeyExistsStmt: %w", cerr)
		}
	}
	if q.countHttpCacheEntriesStmt != nil {
		if cerr := stmtCloseFn(q.countHttpCacheEntriesStmt); cerr != nil {
			err = fmt.Errorf("error closing countHttpCacheEntriesStmt: %w", cerr)
		}
	}
	if q.deleteHttpCacheByIDStmt != nil {
		if cerr := stmtCloseFn(q.deleteHttpCacheByIDStmt); cerr != nil {
			err = fmt.Errorf("error closing deleteHttpCacheByIDStmt: %w", cerr)
		}
	}
	if q.deleteHttpCacheByKeyStmt != nil {
		if cerr := stmtCloseFn(q.deleteHttpCacheByKeyStmt); cerr != nil {
			err = fmt.Errorf("error closing deleteHttpCacheByKeyStmt: %w", cerr)
		}
	}
	if q.deleteHttpCacheExpiredStmt != nil {
		if cerr := stmtCloseFn(q.deleteHttpCacheExpiredStmt); cerr != nil {
			err = fmt.Errorf("error closing deleteHttpCacheExpiredStmt: %w", cerr)
		}
	}
	if q.deleteIPTCStmt != nil {
		if cerr := stmtCloseFn(q.deleteIPTCStmt); cerr != nil {
			err = fmt.Errorf("error closing deleteIPTCStmt: %w", cerr)
		}
	}
	if q.deleteIPTCKeywordStmt != nil {
		if cerr := stmtCloseFn(q.deleteIPTCKeywordStmt); cerr != nil {
			err = fmt.Errorf("error closing deleteIPTCKeywordStmt: %w", cerr)
		}
	}
	if q.deleteInvalidFileByPathStmt != nil {
		if cerr := stmtCloseFn(q.deleteInvalidFileByPathStmt); cerr != nil {
			err = fmt.Errorf("error closing deleteInvalidFileByPathStmt: %w", cerr)
		}
	}
	if q.deleteXMPPropertyStmt != nil {
		if cerr := stmtCloseFn(q.deleteXMPPropertyStmt); cerr != nil {
			err = fmt.Errorf("error closing deleteXMPPropertyStmt: %w", cerr)
		}
	}
	if q.deleteXMPRawStmt != nil {
		if cerr := stmtCloseFn(q.deleteXMPRawStmt); cerr != nil {
			err = fmt.Errorf("error closing deleteXMPRawStmt: %w", cerr)
		}
	}
	if q.getConfigValueByKeyStmt != nil {
		if cerr := stmtCloseFn(q.getConfigValueByKeyStmt); cerr != nil {
			err = fmt.Errorf("error closing getConfigValueByKeyStmt: %w", cerr)
		}
	}
	if q.getConfigsStmt != nil {
		if cerr := stmtCloseFn(q.getConfigsStmt); cerr != nil {
			err = fmt.Errorf("error closing getConfigsStmt: %w", cerr)
		}
	}
	if q.getExifByFileStmt != nil {
		if cerr := stmtCloseFn(q.getExifByFileStmt); cerr != nil {
			err = fmt.Errorf("error closing getExifByFileStmt: %w", cerr)
		}
	}
	if q.getFileByPathStmt != nil {
		if cerr := stmtCloseFn(q.getFileByPathStmt); cerr != nil {
			err = fmt.Errorf("error closing getFileByPathStmt: %w", cerr)
		}
	}
	if q.getFileViewByIDStmt != nil {
		if cerr := stmtCloseFn(q.getFileViewByIDStmt); cerr != nil {
			err = fmt.Errorf("error closing getFileViewByIDStmt: %w", cerr)
		}
	}
	if q.getFileViewsByFolderIDOrderByFileNameStmt != nil {
		if cerr := stmtCloseFn(q.getFileViewsByFolderIDOrderByFileNameStmt); cerr != nil {
			err = fmt.Errorf("error closing getFileViewsByFolderIDOrderByFileNameStmt: %w", cerr)
		}
	}
	if q.getFolderByIDStmt != nil {
		if cerr := stmtCloseFn(q.getFolderByIDStmt); cerr != nil {
			err = fmt.Errorf("error closing getFolderByIDStmt: %w", cerr)
		}
	}
	if q.getFolderByPathStmt != nil {
		if cerr := stmtCloseFn(q.getFolderByPathStmt); cerr != nil {
			err = fmt.Errorf("error closing getFolderByPathStmt: %w", cerr)
		}
	}
	if q.getFolderIDByPathStmt != nil {
		if cerr := stmtCloseFn(q.getFolderIDByPathStmt); cerr != nil {
			err = fmt.Errorf("error closing getFolderIDByPathStmt: %w", cerr)
		}
	}
	if q.getFolderTileExistsViewByPathStmt != nil {
		if cerr := stmtCloseFn(q.getFolderTileExistsViewByPathStmt); cerr != nil {
			err = fmt.Errorf("error closing getFolderTileExistsViewByPathStmt: %w", cerr)
		}
	}
	if q.getFolderViewByIDStmt != nil {
		if cerr := stmtCloseFn(q.getFolderViewByIDStmt); cerr != nil {
			err = fmt.Errorf("error closing getFolderViewByIDStmt: %w", cerr)
		}
	}
	if q.getFoldersViewsByParentIDOrderByNameStmt != nil {
		if cerr := stmtCloseFn(q.getFoldersViewsByParentIDOrderByNameStmt); cerr != nil {
			err = fmt.Errorf("error closing getFoldersViewsByParentIDOrderByNameStmt: %w", cerr)
		}
	}
	if q.getGalleryStatisticsStmt != nil {
		if cerr := stmtCloseFn(q.getGalleryStatisticsStmt); cerr != nil {
			err = fmt.Errorf("error closing getGalleryStatisticsStmt: %w", cerr)
		}
	}
	if q.getHttpCacheByKeyStmt != nil {
		if cerr := stmtCloseFn(q.getHttpCacheByKeyStmt); cerr != nil {
			err = fmt.Errorf("error closing getHttpCacheByKeyStmt: %w", cerr)
		}
	}
	if q.getHttpCacheOldestCreatedStmt != nil {
		if cerr := stmtCloseFn(q.getHttpCacheOldestCreatedStmt); cerr != nil {
			err = fmt.Errorf("error closing getHttpCacheOldestCreatedStmt: %w", cerr)
		}
	}
	if q.getHttpCacheSizeBytesStmt != nil {
		if cerr := stmtCloseFn(q.getHttpCacheSizeBytesStmt); cerr != nil {
			err = fmt.Errorf("error closing getHttpCacheSizeBytesStmt: %w", cerr)
		}
	}
	if q.getIPTCByFileStmt != nil {
		if cerr := stmtCloseFn(q.getIPTCByFileStmt); cerr != nil {
			err = fmt.Errorf("error closing getIPTCByFileStmt: %w", cerr)
		}
	}
	if q.getIPTCKeywordsStmt != nil {
		if cerr := stmtCloseFn(q.getIPTCKeywordsStmt); cerr != nil {
			err = fmt.Errorf("error closing getIPTCKeywordsStmt: %w", cerr)
		}
	}
	if q.getInvalidFileByPathStmt != nil {
		if cerr := stmtCloseFn(q.getInvalidFileByPathStmt); cerr != nil {
			err = fmt.Errorf("error closing getInvalidFileByPathStmt: %w", cerr)
		}
	}
	if q.getLoginAttemptStmt != nil {
		if cerr := stmtCloseFn(q.getLoginAttemptStmt); cerr != nil {
			err = fmt.Errorf("error closing getLoginAttemptStmt: %w", cerr)
		}
	}
	if q.getModuleStateStmt != nil {
		if cerr := stmtCloseFn(q.getModuleStateStmt); cerr != nil {
			err = fmt.Errorf("error closing getModuleStateStmt: %w", cerr)
		}
	}
	if q.getThumbnailExistsViewByIDStmt != nil {
		if cerr := stmtCloseFn(q.getThumbnailExistsViewByIDStmt); cerr != nil {
			err = fmt.Errorf("error closing getThumbnailExistsViewByIDStmt: %w", cerr)
		}
	}
	if q.getThumbnailsByFileIDStmt != nil {
		if cerr := stmtCloseFn(q.getThumbnailsByFileIDStmt); cerr != nil {
			err = fmt.Errorf("error closing getThumbnailsByFileIDStmt: %w", cerr)
		}
	}
	if q.getXMPPropertiesByFileStmt != nil {
		if cerr := stmtCloseFn(q.getXMPPropertiesByFileStmt); cerr != nil {
			err = fmt.Errorf("error closing getXMPPropertiesByFileStmt: %w", cerr)
		}
	}
	if q.getXMPRawStmt != nil {
		if cerr := stmtCloseFn(q.getXMPRawStmt); cerr != nil {
			err = fmt.Errorf("error closing getXMPRawStmt: %w", cerr)
		}
	}
	if q.httpCacheExistsByKeyStmt != nil {
		if cerr := stmtCloseFn(q.httpCacheExistsByKeyStmt); cerr != nil {
			err = fmt.Errorf("error closing httpCacheExistsByKeyStmt: %w", cerr)
		}
	}
	if q.insertConfigIfNotExistsStmt != nil {
		if cerr := stmtCloseFn(q.insertConfigIfNotExistsStmt); cerr != nil {
			err = fmt.Errorf("error closing insertConfigIfNotExistsStmt: %w", cerr)
		}
	}
	if q.insertIPTCKeywordStmt != nil {
		if cerr := stmtCloseFn(q.insertIPTCKeywordStmt); cerr != nil {
			err = fmt.Errorf("error closing insertIPTCKeywordStmt: %w", cerr)
		}
	}
	if q.setModuleStateStmt != nil {
		if cerr := stmtCloseFn(q.setModuleStateStmt); cerr != nil {
			err = fmt.Errorf("error closing setModuleStateStmt: %w", cerr)
		}
	}
	if q.unlockAccountStmt != nil {
		if cerr := stmtCloseFn(q.unlockAccountStmt); cerr != nil {
			err = fmt.Errorf("error closing unlockAccountStmt: %w", cerr)
		}
	}
	if q.updateFolderTileIdStmt != nil {
		if cerr := stmtCloseFn(q.updateFolderTileIdStmt); cerr != nil {
			err = fmt.Errorf("error closing updateFolderTileIdStmt: %w", cerr)
		}
	}
	if q.upsertConfigValueOnlyStmt != nil {
		if cerr := stmtCloseFn(q.upsertConfigValueOnlyStmt); cerr != nil {
			err = fmt.Errorf("error closing upsertConfigValueOnlyStmt: %w", cerr)
		}
	}
	if q.upsertExifStmt != nil {
		if cerr := stmtCloseFn(q.upsertExifStmt); cerr != nil {
			err = fmt.Errorf("error closing upsertExifStmt: %w", cerr)
		}
	}
	if q.upsertFilePathReturningIDStmt != nil {
		if cerr := stmtCloseFn(q.upsertFilePathReturningIDStmt); cerr != nil {
			err = fmt.Errorf("error closing upsertFilePathReturningIDStmt: %w", cerr)
		}
	}
	if q.upsertFileReturningFileStmt != nil {
		if cerr := stmtCloseFn(q.upsertFileReturningFileStmt); cerr != nil {
			err = fmt.Errorf("error closing upsertFileReturningFileStmt: %w", cerr)
		}
	}
	if q.upsertFolderPathReturningIDStmt != nil {
		if cerr := stmtCloseFn(q.upsertFolderPathReturningIDStmt); cerr != nil {
			err = fmt.Errorf("error closing upsertFolderPathReturningIDStmt: %w", cerr)
		}
	}
	if q.upsertFolderReturningFolderStmt != nil {
		if cerr := stmtCloseFn(q.upsertFolderReturningFolderStmt); cerr != nil {
			err = fmt.Errorf("error closing upsertFolderReturningFolderStmt: %w", cerr)
		}
	}
	if q.upsertHttpCacheStmt != nil {
		if cerr := stmtCloseFn(q.upsertHttpCacheStmt); cerr != nil {
			err = fmt.Errorf("error closing upsertHttpCacheStmt: %w", cerr)
		}
	}
	if q.upsertIPTCStmt != nil {
		if cerr := stmtCloseFn(q.upsertIPTCStmt); cerr != nil {
			err = fmt.Errorf("error closing upsertIPTCStmt: %w", cerr)
		}
	}
	if q.upsertInvalidFileStmt != nil {
		if cerr := stmtCloseFn(q.upsertInvalidFileStmt); cerr != nil {
			err = fmt.Errorf("error closing upsertInvalidFileStmt: %w", cerr)
		}
	}
	if q.upsertLoginAttemptStmt != nil {
		if cerr := stmtCloseFn(q.upsertLoginAttemptStmt); cerr != nil {
			err = fmt.Errorf("error closing upsertLoginAttemptStmt: %w", cerr)
		}
	}
	if q.upsertThumbnailReturningIDStmt != nil {
		if cerr := stmtCloseFn(q.upsertThumbnailReturningIDStmt); cerr != nil {
			err = fmt.Errorf("error closing upsertThumbnailReturningIDStmt: %w", cerr)
		}
	}
	if q.upsertXMPPropertyStmt != nil {
		if cerr := stmtCloseFn(q.upsertXMPPropertyStmt); cerr != nil {
			err = fmt.Errorf("error closing upsertXMPPropertyStmt: %w", cerr)
		}
	}
	if q.upsertXMPRawStmt != nil {
		if cerr := stmtCloseFn(q.upsertXMPRawStmt); cerr != nil {
			err = fmt.Errorf("error closing upsertXMPRawStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                        DBTX
	tx                                        *sql.Tx
	clearHttpCacheStmt                        *sql.Stmt
	clearLoginAttemptsStmt                    *sql.Stmt
	configKeyExistsStmt                       *sql.Stmt
	countHttpCacheEntriesStmt                 *sql.Stmt
	deleteHttpCacheByIDStmt                   *sql.Stmt
	deleteHttpCacheByKeyStmt                  *sql.Stmt
	deleteHttpCacheExpiredStmt                *sql.Stmt
	deleteIPTCStmt                            *sql.Stmt
	deleteIPTCKeywordStmt                     *sql.Stmt
	deleteInvalidFileByPathStmt               *sql.Stmt
	deleteXMPPropertyStmt                     *sql.Stmt
	deleteXMPRawStmt                          *sql.Stmt
	getConfigValueByKeyStmt                   *sql.Stmt
	getConfigsStmt                            *sql.Stmt
	getExifByFileStmt                         *sql.Stmt
	getFileByPathStmt                         *sql.Stmt
	getFileViewByIDStmt                       *sql.Stmt
	getFileViewsByFolderIDOrderByFileNameStmt *sql.Stmt
	getFolderByIDStmt                         *sql.Stmt
	getFolderByPathStmt                       *sql.Stmt
	getFolderIDByPathStmt                     *sql.Stmt
	getFolderTileExistsViewByPathStmt         *sql.Stmt
	getFolderViewByIDStmt                     *sql.Stmt
	getFoldersViewsByParentIDOrderByNameStmt  *sql.Stmt
	getGalleryStatisticsStmt                  *sql.Stmt
	getHttpCacheByKeyStmt                     *sql.Stmt
	getHttpCacheOldestCreatedStmt             *sql.Stmt
	getHttpCacheSizeBytesStmt                 *sql.Stmt
	getIPTCByFileStmt                         *sql.Stmt
	getIPTCKeywordsStmt                       *sql.Stmt
	getInvalidFileByPathStmt                  *sql.Stmt
	getLoginAttemptStmt                       *sql.Stmt
	getModuleStateStmt                        *sql.Stmt
	getThumbnailExistsViewByIDStmt            *sql.Stmt
	getThumbnailsByFileIDStmt                 *sql.Stmt
	getXMPPropertiesByFileStmt                *sql.Stmt
	getXMPRawStmt                             *sql.Stmt
	httpCacheExistsByKeyStmt                  *sql.Stmt
	insertConfigIfNotExistsStmt               *sql.Stmt
	insertIPTCKeywordStmt                     *sql.Stmt
	setModuleStateStmt                        *sql.Stmt
	unlockAccountStmt                         *sql.Stmt
	updateFolderTileIdStmt                    *sql.Stmt
	upsertConfigValueOnlyStmt                 *sql.Stmt
	upsertExifStmt                            *sql.Stmt
	upsertFilePathReturningIDStmt             *sql.Stmt
	upsertFileReturningFileStmt               *sql.Stmt
	upsertFolderPathReturningIDStmt           *sql.Stmt
	upsertFolderReturningFolderStmt           *sql.Stmt
	upsertHttpCacheStmt                       *sql.Stmt
	upsertIPTCStmt                            *sql.Stmt
	upsertInvalidFileStmt                     *sql.Stmt
	upsertLoginAttemptStmt                    *sql.Stmt
	upsertThumbnailReturningIDStmt            *sql.Stmt
	upsertXMPPropertyStmt                     *sql.Stmt
	upsertXMPRawStmt                          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                          tx,
		tx:                          tx,
		clearHttpCacheStmt:          q.clearHttpCacheStmt,
		clearLoginAttemptsStmt:      q.clearLoginAttemptsStmt,
		configKeyExistsStmt:         q.configKeyExistsStmt,
		countHttpCacheEntriesStmt:   q.countHttpCacheEntriesStmt,
		deleteHttpCacheByIDStmt:     q.deleteHttpCacheByIDStmt,
		deleteHttpCacheByKeyStmt:    q.deleteHttpCacheByKeyStmt,
		deleteHttpCacheExpiredStmt:  q.deleteHttpCacheExpiredStmt,
		deleteIPTCStmt:              q.deleteIPTCStmt,
		deleteIPTCKeywordStmt:       q.deleteIPTCKeywordStmt,
		deleteInvalidFileByPathStmt: q.deleteInvalidFileByPathStmt,
		deleteXMPPropertyStmt:       q.deleteXMPPropertyStmt,
		deleteXMPRawStmt:            q.deleteXMPRawStmt,
		getConfigValueByKeyStmt:     q.getConfigValueByKeyStmt,
		getConfigsStmt:              q.getConfigsStmt,
		getExifByFileStmt:           q.getExifByFileStmt,
		getFileByPathStmt:           q.getFileByPathStmt,
		getFileViewByIDStmt:         q.getFileViewByIDStmt,
		getFileViewsByFolderIDOrderByFileNameStmt: q.getFileViewsByFolderIDOrderByFileNameStmt,
		getFolderByIDStmt:                         q.getFolderByIDStmt,
		getFolderByPathStmt:                       q.getFolderByPathStmt,
		getFolderIDByPathStmt:                     q.getFolderIDByPathStmt,
		getFolderTileExistsViewByPathStmt:         q.getFolderTileExistsViewByPathStmt,
		getFolderViewByIDStmt:                     q.getFolderViewByIDStmt,
		getFoldersViewsByParentIDOrderByNameStmt:  q.getFoldersViewsByParentIDOrderByNameStmt,
		getGalleryStatisticsStmt:                  q.getGalleryStatisticsStmt,
		getHttpCacheByKeyStmt:                     q.getHttpCacheByKeyStmt,
		getHttpCacheOldestCreatedStmt:             q.getHttpCacheOldestCreatedStmt,
		getHttpCacheSizeBytesStmt:                 q.getHttpCacheSizeBytesStmt,
		getIPTCByFileStmt:                         q.getIPTCByFileStmt,
		getIPTCKeywordsStmt:                       q.getIPTCKeywordsStmt,
		getInvalidFileByPathStmt:                  q.getInvalidFileByPathStmt,
		getLoginAttemptStmt:                       q.getLoginAttemptStmt,
		getModuleStateStmt:                        q.getModuleStateStmt,
		getThumbnailExistsViewByIDStmt:            q.getThumbnailExistsViewByIDStmt,
		getThumbnailsByFileIDStmt:                 q.getThumbnailsByFileIDStmt,
		getXMPPropertiesByFileStmt:                q.getXMPPropertiesByFileStmt,
		getXMPRawStmt:                             q.getXMPRawStmt,
		httpCacheExistsByKeyStmt:                  q.httpCacheExistsByKeyStmt,
		insertConfigIfNotExistsStmt:               q.insertConfigIfNotExistsStmt,
		insertIPTCKeywordStmt:                     q.insertIPTCKeywordStmt,
		setModuleStateStmt:                        q.setModuleStateStmt,
		unlockAccountStmt:                         q.unlockAccountStmt,
		updateFolderTileIdStmt:                    q.updateFolderTileIdStmt,
		upsertConfigValueOnlyStmt:                 q.upsertConfigValueOnlyStmt,
		upsertExifStmt:                            q.upsertExifStmt,
		upsertFilePathReturningIDStmt:             q.upsertFilePathReturningIDStmt,
		upsertFileReturningFileStmt:               q.upsertFileReturningFileStmt,
		upsertFolderPathReturningIDStmt:           q.upsertFolderPathReturningIDStmt,
		upsertFolderReturningFolderStmt:           q.upsertFolderReturningFolderStmt,
		upsertHttpCacheStmt:                       q.upsertHttpCacheStmt,
		upsertIPTCStmt:                            q.upsertIPTCStmt,
		upsertInvalidFileStmt:                     q.upsertInvalidFileStmt,
		upsertLoginAttemptStmt:                    q.upsertLoginAttemptStmt,
		upsertThumbnailReturningIDStmt:            q.upsertThumbnailReturningIDStmt,
		upsertXMPPropertyStmt:                     q.upsertXMPPropertyStmt,
		upsertXMPRawStmt:                          q.upsertXMPRawStmt,
	}
}
