// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exif.sql

package gallerydb

import (
	"context"
	"database/sql"
)

const getExifByFile = `-- name: GetExifByFile :one
SELECT file_id, camera_make, camera_model, lens_model, focal_length, aperture, shutter_speed, iso, orientation, latitude, longitude, altitude, capture_date, software FROM exif_metadata WHERE file_id = ?
`

func (q *Queries) GetExifByFile(ctx context.Context, fileID int64) (ExifMetadatum, error) {
	row := q.queryRow(ctx, q.getExifByFileStmt, getExifByFile, fileID)
	var i ExifMetadatum
	err := row.Scan(
		&i.FileID,
		&i.CameraMake,
		&i.CameraModel,
		&i.LensModel,
		&i.FocalLength,
		&i.Aperture,
		&i.ShutterSpeed,
		&i.Iso,
		&i.Orientation,
		&i.Latitude,
		&i.Longitude,
		&i.Altitude,
		&i.CaptureDate,
		&i.Software,
	)
	return i, err
}

const upsertExif = `-- name: UpsertExif :exec
INSERT INTO exif_metadata (file_id, camera_make, camera_model, lens_model,
                           focal_length, aperture, shutter_speed, iso,
                           orientation, latitude, longitude, altitude, capture_date)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(file_id) DO UPDATE SET
  camera_make=excluded.camera_make,
  camera_model=excluded.camera_model,
  lens_model=excluded.lens_model,
  focal_length=excluded.focal_length,
  aperture=excluded.aperture,
  shutter_speed=excluded.shutter_speed,
  iso=excluded.iso,
  orientation=excluded.orientation,
  latitude=excluded.latitude,
  longitude=excluded.longitude,
  altitude=excluded.altitude,
  capture_date=excluded.capture_date
`

type UpsertExifParams struct {
	FileID       int64
	CameraMake   sql.NullString
	CameraModel  sql.NullString
	LensModel    sql.NullString
	FocalLength  sql.NullString
	Aperture     sql.NullString
	ShutterSpeed sql.NullString
	Iso          sql.NullInt64
	Orientation  sql.NullInt64
	Latitude     sql.NullFloat64
	Longitude    sql.NullFloat64
	Altitude     sql.NullFloat64
	CaptureDate  sql.NullInt64
}

func (q *Queries) UpsertExif(ctx context.Context, arg UpsertExifParams) error {
	_, err := q.exec(ctx, q.upsertExifStmt, upsertExif,
		arg.FileID,
		arg.CameraMake,
		arg.CameraModel,
		arg.LensModel,
		arg.FocalLength,
		arg.Aperture,
		arg.ShutterSpeed,
		arg.Iso,
		arg.Orientation,
		arg.Latitude,
		arg.Longitude,
		arg.Altitude,
		arg.CaptureDate,
	)
	return err
}
