// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package gallerydb

import (
	"context"
	"database/sql"
)

const getFileByPath = `-- name: GetFileByPath :one
SELECT f.id, f.folder_id, f.path_id, f.filename, f.size_bytes, f.mtime, f.md5, f.phash, f.mime_type, f.width, f.height, f.created_at, f.updated_at 
  FROM file_paths fp
       INNER JOIN files f  
          ON fp.id = f.path_id 
  WHERE fp.path = ?
`

func (q *Queries) GetFileByPath(ctx context.Context, path string) (File, error) {
	row := q.queryRow(ctx, q.getFileByPathStmt, getFileByPath, path)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.PathID,
		&i.Filename,
		&i.SizeBytes,
		&i.Mtime,
		&i.Md5,
		&i.Phash,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileViewByID = `-- name: GetFileViewByID :one
SELECT id, folder_id, folder_path, path, filename, size_bytes, mtime, md5, phash, mime_type, width, height, created_at, updated_at
  FROM file_view
 WHERE id = ?
`

func (q *Queries) GetFileViewByID(ctx context.Context, id int64) (FileView, error) {
	row := q.queryRow(ctx, q.getFileViewByIDStmt, getFileViewByID, id)
	var i FileView
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.FolderPath,
		&i.Path,
		&i.Filename,
		&i.SizeBytes,
		&i.Mtime,
		&i.Md5,
		&i.Phash,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileViewsByFolderIDOrderByFileName = `-- name: GetFileViewsByFolderIDOrderByFileName :many
SELECT id, folder_id, folder_path, path, filename, size_bytes, mtime, md5, phash, mime_type, width, height, created_at, updated_at
  FROM file_view
 WHERE folder_id = ?
 ORDER BY filename
`

func (q *Queries) GetFileViewsByFolderIDOrderByFileName(ctx context.Context, folderID sql.NullInt64) ([]FileView, error) {
	rows, err := q.query(ctx, q.getFileViewsByFolderIDOrderByFileNameStmt, getFileViewsByFolderIDOrderByFileName, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileView
	for rows.Next() {
		var i FileView
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.FolderPath,
			&i.Path,
			&i.Filename,
			&i.SizeBytes,
			&i.Mtime,
			&i.Md5,
			&i.Phash,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFileReturningFile = `-- name: UpsertFileReturningFile :one
INSERT INTO files (folder_id, path_id, filename, size_bytes, mtime, md5, phash, mime_type, width, height, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ON CONFLICT(path_id) 
    DO UPDATE SET filename   = excluded.filename
                , size_bytes = excluded.size_bytes
                , mtime      = excluded.mtime
                , md5        = excluded.md5
                , phash      = excluded.phash
                , mime_type  = excluded.mime_type
                , width      = excluded.width
                , height     = excluded.height
                , updated_at = excluded.updated_at
RETURNING id, folder_id, path_id, filename, size_bytes, mtime, md5, phash, mime_type, width, height, created_at, updated_at
`

type UpsertFileReturningFileParams struct {
	FolderID  sql.NullInt64
	PathID    int64
	Filename  string
	SizeBytes sql.NullInt64
	Mtime     sql.NullInt64
	Md5       sql.NullString
	Phash     sql.NullInt64
	MimeType  sql.NullString
	Width     sql.NullInt64
	Height    sql.NullInt64
	CreatedAt interface{}
	UpdatedAt interface{}
}

func (q *Queries) UpsertFileReturningFile(ctx context.Context, arg UpsertFileReturningFileParams) (File, error) {
	row := q.queryRow(ctx, q.upsertFileReturningFileStmt, upsertFileReturningFile,
		arg.FolderID,
		arg.PathID,
		arg.Filename,
		arg.SizeBytes,
		arg.Mtime,
		arg.Md5,
		arg.Phash,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.PathID,
		&i.Filename,
		&i.SizeBytes,
		&i.Mtime,
		&i.Md5,
		&i.Phash,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
