// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package gallerydb

import (
	"context"
	"database/sql"
)

const getFileByPath = `-- name: GetFileByPath :one
SELECT f.id, f.folder_id, f.path_id, f.filename, f.size_bytes, f.mtime, f.md5, f.phash, f.mime_type, f.width, f.height, f.created_at, f.updated_at 
  FROM file_paths fp
       INNER JOIN files f  
          ON fp.id = f.path_id 
  WHERE fp.path = ?
`

func (q *Queries) GetFileByPath(ctx context.Context, path string) (File, error) {
	row := q.queryRow(ctx, q.getFileByPathStmt, getFileByPath, path)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.PathID,
		&i.Filename,
		&i.SizeBytes,
		&i.Mtime,
		&i.Md5,
		&i.Phash,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileCountAndTimestamps = `-- name: GetFileCountAndTimestamps :one
SELECT COUNT(*)                                  AS ct_files
     , CAST(COALESCE(MIN(created_at), 0) AS INTEGER) AS min_created_at
     , CAST(COALESCE(MAX(updated_at), 0) AS INTEGER) AS max_updated_at
  FROM files
`

type GetFileCountAndTimestampsRow struct {
	CtFiles      int64
	MinCreatedAt int64
	MaxUpdatedAt int64
}

func (q *Queries) GetFileCountAndTimestamps(ctx context.Context) (GetFileCountAndTimestampsRow, error) {
	row := q.queryRow(ctx, q.getFileCountAndTimestampsStmt, getFileCountAndTimestamps)
	var i GetFileCountAndTimestampsRow
	err := row.Scan(&i.CtFiles, &i.MinCreatedAt, &i.MaxUpdatedAt)
	return i, err
}

const getFileFolderIndexByID = `-- name: GetFileFolderIndexByID :one
WITH target AS (
  SELECT fv.folder_id AS folder_id, fv.id AS id
    FROM file_view fv
   WHERE fv.id = ?
),
ordered AS (
  SELECT fv.id AS id,
         CAST(ROW_NUMBER() OVER (ORDER BY fv.filename, fv.id) AS INTEGER) AS image_index,
         CAST(COUNT(*) OVER () AS INTEGER) AS image_count
    FROM file_view fv
         INNER JOIN target t ON fv.folder_id = t.folder_id
)
SELECT o.image_index, o.image_count
  FROM ordered o
       INNER JOIN target t ON o.id = t.id
`

type GetFileFolderIndexByIDRow struct {
	ImageIndex int64
	ImageCount int64
}

func (q *Queries) GetFileFolderIndexByID(ctx context.Context, id int64) (GetFileFolderIndexByIDRow, error) {
	row := q.queryRow(ctx, q.getFileFolderIndexByIDStmt, getFileFolderIndexByID, id)
	var i GetFileFolderIndexByIDRow
	err := row.Scan(&i.ImageIndex, &i.ImageCount)
	return i, err
}

const getFileSizeSum = `-- name: GetFileSizeSum :one
SELECT CAST(COALESCE(SUM(size_bytes), 0) AS INTEGER) AS sz_files
  FROM files
`

func (q *Queries) GetFileSizeSum(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.getFileSizeSumStmt, getFileSizeSum)
	var sz_files int64
	err := row.Scan(&sz_files)
	return sz_files, err
}

const getFileViewByID = `-- name: GetFileViewByID :one
SELECT id, folder_id, folder_path, path, filename, size_bytes, mtime, md5, phash, mime_type, width, height, created_at, updated_at
  FROM file_view
 WHERE id = ?
`

func (q *Queries) GetFileViewByID(ctx context.Context, id int64) (FileView, error) {
	row := q.queryRow(ctx, q.getFileViewByIDStmt, getFileViewByID, id)
	var i FileView
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.FolderPath,
		&i.Path,
		&i.Filename,
		&i.SizeBytes,
		&i.Mtime,
		&i.Md5,
		&i.Phash,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileViewsByFolderIDOrderByFileName = `-- name: GetFileViewsByFolderIDOrderByFileName :many
SELECT id, folder_id, folder_path, path, filename, size_bytes, mtime, md5, phash, mime_type, width, height, created_at, updated_at
  FROM file_view
 WHERE folder_id = ?
 ORDER BY filename
`

func (q *Queries) GetFileViewsByFolderIDOrderByFileName(ctx context.Context, folderID sql.NullInt64) ([]FileView, error) {
	rows, err := q.query(ctx, q.getFileViewsByFolderIDOrderByFileNameStmt, getFileViewsByFolderIDOrderByFileName, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileView
	for rows.Next() {
		var i FileView
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.FolderPath,
			&i.Path,
			&i.Filename,
			&i.SizeBytes,
			&i.Mtime,
			&i.Md5,
			&i.Phash,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolderCount = `-- name: GetFolderCount :one
SELECT COUNT(*) AS ct FROM folders
`

func (q *Queries) GetFolderCount(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.getFolderCountStmt, getFolderCount)
	var ct int64
	err := row.Scan(&ct)
	return ct, err
}

const getGalleryFileThumbRowsByFolderID = `-- name: GetGalleryFileThumbRowsByFolderID :many
SELECT fv.id AS id, fv.filename AS filename
  FROM file_view fv
 WHERE fv.folder_id = ?
 ORDER BY fv.filename
`

type GetGalleryFileThumbRowsByFolderIDRow struct {
	ID       int64
	Filename string
}

func (q *Queries) GetGalleryFileThumbRowsByFolderID(ctx context.Context, folderID sql.NullInt64) ([]GetGalleryFileThumbRowsByFolderIDRow, error) {
	rows, err := q.query(ctx, q.getGalleryFileThumbRowsByFolderIDStmt, getGalleryFileThumbRowsByFolderID, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGalleryFileThumbRowsByFolderIDRow
	for rows.Next() {
		var i GetGalleryFileThumbRowsByFolderIDRow
		if err := rows.Scan(&i.ID, &i.Filename); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLightboxNavByFileID = `-- name: GetLightboxNavByFileID :one
WITH target AS (
  SELECT fv.folder_id AS folder_id, fv.id AS id
    FROM file_view fv
   WHERE fv.id = ?
),
ordered AS (
  SELECT fv.id AS id,
         CAST(ROW_NUMBER() OVER (ORDER BY fv.filename, fv.id) - 1 AS INTEGER) AS current_index,
         CAST(COUNT(*) OVER () AS INTEGER) AS image_count,
         CAST(LAG(fv.id) OVER (ORDER BY fv.filename, fv.id) AS INTEGER) AS prev_id,
         CAST(LEAD(fv.id) OVER (ORDER BY fv.filename, fv.id) AS INTEGER) AS next_id,
         CAST(FIRST_VALUE(fv.id) OVER (ORDER BY fv.filename, fv.id) AS INTEGER) AS first_id,
         CAST(LAST_VALUE(fv.id) OVER (
           ORDER BY fv.filename, fv.id
           ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
         ) AS INTEGER) AS last_id
    FROM file_view fv
         INNER JOIN target t ON fv.folder_id = t.folder_id
)
SELECT o.current_index, o.image_count, o.first_id, o.last_id, o.prev_id, o.next_id
  FROM ordered o
       INNER JOIN target t ON o.id = t.id
`

type GetLightboxNavByFileIDRow struct {
	CurrentIndex int64
	ImageCount   int64
	FirstID      int64
	LastID       int64
	PrevID       sql.NullInt64
	NextID       sql.NullInt64
}

func (q *Queries) GetLightboxNavByFileID(ctx context.Context, id int64) (GetLightboxNavByFileIDRow, error) {
	row := q.queryRow(ctx, q.getLightboxNavByFileIDStmt, getLightboxNavByFileID, id)
	var i GetLightboxNavByFileIDRow
	err := row.Scan(
		&i.CurrentIndex,
		&i.ImageCount,
		&i.FirstID,
		&i.LastID,
		&i.PrevID,
		&i.NextID,
	)
	return i, err
}

const upsertFileReturningFile = `-- name: UpsertFileReturningFile :one
INSERT INTO files (folder_id, path_id, filename, size_bytes, mtime, md5, phash, mime_type, width, height, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ON CONFLICT(path_id) 
    DO UPDATE SET filename   = excluded.filename
                , size_bytes = excluded.size_bytes
                , mtime      = excluded.mtime
                , md5        = excluded.md5
                , phash      = excluded.phash
                , mime_type  = excluded.mime_type
                , width      = excluded.width
                , height     = excluded.height
                , updated_at = excluded.updated_at
RETURNING id, folder_id, path_id, filename, size_bytes, mtime, md5, phash, mime_type, width, height, created_at, updated_at
`

type UpsertFileReturningFileParams struct {
	FolderID  sql.NullInt64
	PathID    int64
	Filename  string
	SizeBytes sql.NullInt64
	Mtime     sql.NullInt64
	Md5       sql.NullString
	Phash     sql.NullInt64
	MimeType  sql.NullString
	Width     sql.NullInt64
	Height    sql.NullInt64
	CreatedAt interface{}
	UpdatedAt interface{}
}

func (q *Queries) UpsertFileReturningFile(ctx context.Context, arg UpsertFileReturningFileParams) (File, error) {
	row := q.queryRow(ctx, q.upsertFileReturningFileStmt, upsertFileReturningFile,
		arg.FolderID,
		arg.PathID,
		arg.Filename,
		arg.SizeBytes,
		arg.Mtime,
		arg.Md5,
		arg.Phash,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.PathID,
		&i.Filename,
		&i.SizeBytes,
		&i.Mtime,
		&i.Md5,
		&i.Phash,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
