// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folders.sql

package gallerydb

import (
	"context"
	"database/sql"
)

const getFolderByID = `-- name: GetFolderByID :one

SELECT id, parent_id, path_id, name, mtime, tile_id, created_at, updated_at
  FROM folders
 WHERE id = ?
`

// -- name: PopulateMissingTileID :exec
// UPDATE folders
//
//	  SET tile_id = (
//	    SELECT tile_id
//	      FROM (
//	        SELECT f.id, p.id AS tile_id
//	             , DENSE_RANK() OVER (PARTITION BY f.id ORDER BY p.path) AS rnk
//	          FROM files f
//	               INNER JOIN file_paths p
//	                 ON f.path_id = p.id
//	         WHERE f.tile_id IS NULL
//	      ) ranked
//	     WHERE ranked.id = folders.id
//	       AND ranked.rnk = 1
//	  )
//	WHERE EXISTS (
//	    SELECT 1 FROM files f
//	    WHERE f.tile_id IS NULL AND folders.id = f.id
//	  );
func (q *Queries) GetFolderByID(ctx context.Context, id int64) (Folder, error) {
	row := q.queryRow(ctx, q.getFolderByIDStmt, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.PathID,
		&i.Name,
		&i.Mtime,
		&i.TileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderByPath = `-- name: GetFolderByPath :one
SELECT f.id, f.parent_id, f.path_id, f.name, f.mtime, f.tile_id, f.created_at, f.updated_at
  FROM folders f 
       INNER JOIN folder_paths p 
          ON f.path_id = p.id
 WHERE p.path = ?
`

func (q *Queries) GetFolderByPath(ctx context.Context, path string) (Folder, error) {
	row := q.queryRow(ctx, q.getFolderByPathStmt, getFolderByPath, path)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.PathID,
		&i.Name,
		&i.Mtime,
		&i.TileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderIDByPath = `-- name: GetFolderIDByPath :one
SELECT id 
  FROM folders
 WHERE path_id = (SELECT id FROM folder_paths WHERE path = ?)
`

func (q *Queries) GetFolderIDByPath(ctx context.Context, path string) (int64, error) {
	row := q.queryRow(ctx, q.getFolderIDByPathStmt, getFolderIDByPath, path)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getFolderTileExistsViewByPath = `-- name: GetFolderTileExistsViewByPath :one
SELECT found 
  FROM folder_tile_exists_view
 WHERE path = ?
`

func (q *Queries) GetFolderTileExistsViewByPath(ctx context.Context, path string) (bool, error) {
	row := q.queryRow(ctx, q.getFolderTileExistsViewByPathStmt, getFolderTileExistsViewByPath, path)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const getFolderViewByID = `-- name: GetFolderViewByID :one
SELECT id, parent_id, path, name, mtime, created_at, updated_at 
  FROM folder_view
 WHERE id = ?
`

func (q *Queries) GetFolderViewByID(ctx context.Context, id int64) (FolderView, error) {
	row := q.queryRow(ctx, q.getFolderViewByIDStmt, getFolderViewByID, id)
	var i FolderView
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Path,
		&i.Name,
		&i.Mtime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFoldersViewsByParentIDOrderByName = `-- name: GetFoldersViewsByParentIDOrderByName :many
SELECT id, parent_id, path, name, mtime, created_at, updated_at 
  FROM folder_view
 WHERE parent_id = ?
 ORDER BY name
`

func (q *Queries) GetFoldersViewsByParentIDOrderByName(ctx context.Context, parentID sql.NullInt64) ([]FolderView, error) {
	rows, err := q.query(ctx, q.getFoldersViewsByParentIDOrderByNameStmt, getFoldersViewsByParentIDOrderByName, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FolderView
	for rows.Next() {
		var i FolderView
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Path,
			&i.Name,
			&i.Mtime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFolderTileId = `-- name: UpdateFolderTileId :exec
UPDATE folders 
   SET tile_id = ?
 WHERE id = ?
`

type UpdateFolderTileIdParams struct {
	TileID sql.NullInt64
	ID     int64
}

func (q *Queries) UpdateFolderTileId(ctx context.Context, arg UpdateFolderTileIdParams) error {
	_, err := q.exec(ctx, q.updateFolderTileIdStmt, updateFolderTileId, arg.TileID, arg.ID)
	return err
}

const upsertFolderReturningFolder = `-- name: UpsertFolderReturningFolder :one
INSERT INTO folders (parent_id, path_id, name, mtime, tile_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
    ON CONFLICT (path_id) 
    DO UPDATE 
          SET name = EXCLUDED.name
            , parent_id = EXCLUDED.parent_id
            , mtime = EXCLUDED.mtime
            , tile_id = EXCLUDED.tile_id
            , updated_at = EXCLUDED.updated_at
RETURNING id, parent_id, path_id, name, mtime, tile_id, created_at, updated_at
`

type UpsertFolderReturningFolderParams struct {
	ParentID  sql.NullInt64
	PathID    int64
	Name      string
	Mtime     sql.NullInt64
	TileID    sql.NullInt64
	CreatedAt interface{}
	UpdatedAt interface{}
}

func (q *Queries) UpsertFolderReturningFolder(ctx context.Context, arg UpsertFolderReturningFolderParams) (Folder, error) {
	row := q.queryRow(ctx, q.upsertFolderReturningFolderStmt, upsertFolderReturningFolder,
		arg.ParentID,
		arg.PathID,
		arg.Name,
		arg.Mtime,
		arg.TileID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.PathID,
		&i.Name,
		&i.Mtime,
		&i.TileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
