// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folder_paths.sql

package gallerydb

import (
	"context"
)

const upsertFolderPathReturningID = `-- name: UpsertFolderPathReturningID :one
INSERT INTO folder_paths (path)
VALUES (?)
ON CONFLICT (path) DO UPDATE SET path=excluded.path -- This ensures an ID is returned on conflict
RETURNING id
`

func (q *Queries) UpsertFolderPathReturningID(ctx context.Context, path string) (int64, error) {
	row := q.queryRow(ctx, q.upsertFolderPathReturningIDStmt, upsertFolderPathReturningID, path)
	var id int64
	err := row.Scan(&id)
	return id, err
}
