// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: http_cache.sql

package gallerydb

import (
	"context"
	"database/sql"
)

const clearHttpCache = `-- name: ClearHttpCache :exec
DELETE FROM http_cache
`

func (q *Queries) ClearHttpCache(ctx context.Context) error {
	_, err := q.exec(ctx, q.clearHttpCacheStmt, clearHttpCache)
	return err
}

const countHttpCacheEntries = `-- name: CountHttpCacheEntries :one
SELECT COUNT(*) as count FROM http_cache
`

func (q *Queries) CountHttpCacheEntries(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countHttpCacheEntriesStmt, countHttpCacheEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteHttpCacheByID = `-- name: DeleteHttpCacheByID :exec
DELETE FROM http_cache WHERE id = ?
`

func (q *Queries) DeleteHttpCacheByID(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteHttpCacheByIDStmt, deleteHttpCacheByID, id)
	return err
}

const deleteHttpCacheByKey = `-- name: DeleteHttpCacheByKey :exec
DELETE FROM http_cache WHERE key = ?
`

func (q *Queries) DeleteHttpCacheByKey(ctx context.Context, key string) error {
	_, err := q.exec(ctx, q.deleteHttpCacheByKeyStmt, deleteHttpCacheByKey, key)
	return err
}

const deleteHttpCacheExpired = `-- name: DeleteHttpCacheExpired :exec
DELETE FROM http_cache 
WHERE expires_at IS NOT NULL AND expires_at <= unixepoch()
`

func (q *Queries) DeleteHttpCacheExpired(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteHttpCacheExpiredStmt, deleteHttpCacheExpired)
	return err
}

const getHttpCacheByKey = `-- name: GetHttpCacheByKey :one
SELECT id, "key", method, path, query_string, encoding, status, content_type, cache_control, etag, last_modified, vary, body, content_length, created_at, expires_at, content_encoding FROM http_cache 
WHERE key = ? AND (expires_at IS NULL OR expires_at > unixepoch())
LIMIT 1
`

// queries for HTTP cache table operations
func (q *Queries) GetHttpCacheByKey(ctx context.Context, key string) (HttpCache, error) {
	row := q.queryRow(ctx, q.getHttpCacheByKeyStmt, getHttpCacheByKey, key)
	var i HttpCache
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Method,
		&i.Path,
		&i.QueryString,
		&i.Encoding,
		&i.Status,
		&i.ContentType,
		&i.CacheControl,
		&i.Etag,
		&i.LastModified,
		&i.Vary,
		&i.Body,
		&i.ContentLength,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ContentEncoding,
	)
	return i, err
}

const getHttpCacheOldestCreated = `-- name: GetHttpCacheOldestCreated :many
SELECT id, created_at, content_length FROM http_cache 
ORDER BY created_at ASC 
LIMIT ?
`

type GetHttpCacheOldestCreatedRow struct {
	ID            int64
	CreatedAt     int64
	ContentLength sql.NullInt64
}

func (q *Queries) GetHttpCacheOldestCreated(ctx context.Context, limit int64) ([]GetHttpCacheOldestCreatedRow, error) {
	rows, err := q.query(ctx, q.getHttpCacheOldestCreatedStmt, getHttpCacheOldestCreated, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHttpCacheOldestCreatedRow
	for rows.Next() {
		var i GetHttpCacheOldestCreatedRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.ContentLength); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHttpCacheSizeBytes = `-- name: GetHttpCacheSizeBytes :one
SELECT COALESCE(SUM(content_length), 0) as total_bytes FROM http_cache
`

func (q *Queries) GetHttpCacheSizeBytes(ctx context.Context) (interface{}, error) {
	row := q.queryRow(ctx, q.getHttpCacheSizeBytesStmt, getHttpCacheSizeBytes)
	var total_bytes interface{}
	err := row.Scan(&total_bytes)
	return total_bytes, err
}

const httpCacheExistsByKey = `-- name: HttpCacheExistsByKey :one
SELECT EXISTS(
  SELECT 1 FROM http_cache 
  WHERE key = ? AND (expires_at IS NULL OR expires_at > unixepoch())
) AS found
`

func (q *Queries) HttpCacheExistsByKey(ctx context.Context, key string) (int64, error) {
	row := q.queryRow(ctx, q.httpCacheExistsByKeyStmt, httpCacheExistsByKey, key)
	var found int64
	err := row.Scan(&found)
	return found, err
}

const upsertHttpCache = `-- name: UpsertHttpCache :exec
INSERT INTO http_cache (
  key, method, path, query_string, encoding, status, 
  content_type, content_encoding, cache_control, etag, last_modified, vary, 
  body, content_length, created_at, expires_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(key) DO UPDATE SET 
  status=excluded.status,
  body=excluded.body,
  content_length=excluded.content_length,
  expires_at=excluded.expires_at
`

type UpsertHttpCacheParams struct {
	Key             string
	Method          string
	Path            string
	QueryString     sql.NullString
	Encoding        string
	Status          int64
	ContentType     sql.NullString
	ContentEncoding sql.NullString
	CacheControl    sql.NullString
	Etag            sql.NullString
	LastModified    sql.NullString
	Vary            sql.NullString
	Body            []byte
	ContentLength   sql.NullInt64
	CreatedAt       int64
	ExpiresAt       sql.NullInt64
}

func (q *Queries) UpsertHttpCache(ctx context.Context, arg UpsertHttpCacheParams) error {
	_, err := q.exec(ctx, q.upsertHttpCacheStmt, upsertHttpCache,
		arg.Key,
		arg.Method,
		arg.Path,
		arg.QueryString,
		arg.Encoding,
		arg.Status,
		arg.ContentType,
		arg.ContentEncoding,
		arg.CacheControl,
		arg.Etag,
		arg.LastModified,
		arg.Vary,
		arg.Body,
		arg.ContentLength,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}
