// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invalid_files.sql

package gallerydb

import (
	"context"
	"database/sql"
)

const deleteInvalidFileByPath = `-- name: DeleteInvalidFileByPath :exec
DELETE FROM invalid_files WHERE path = ?
`

func (q *Queries) DeleteInvalidFileByPath(ctx context.Context, path string) error {
	_, err := q.exec(ctx, q.deleteInvalidFileByPathStmt, deleteInvalidFileByPath, path)
	return err
}

const getInvalidFileByPath = `-- name: GetInvalidFileByPath :one
SELECT path, mtime, size, reason, created_at, updated_at FROM invalid_files WHERE path = ?
`

func (q *Queries) GetInvalidFileByPath(ctx context.Context, path string) (InvalidFile, error) {
	row := q.queryRow(ctx, q.getInvalidFileByPathStmt, getInvalidFileByPath, path)
	var i InvalidFile
	err := row.Scan(
		&i.Path,
		&i.Mtime,
		&i.Size,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInvalidFile = `-- name: UpsertInvalidFile :exec
INSERT INTO invalid_files (path, mtime, size, reason, updated_at)
VALUES (?, ?, ?, ?, UNIXEPOCH('now'))
ON CONFLICT(path) DO UPDATE SET
    mtime = excluded.mtime,
    size = excluded.size,
    reason = excluded.reason,
    updated_at = UNIXEPOCH('now')
`

type UpsertInvalidFileParams struct {
	Path   string
	Mtime  int64
	Size   int64
	Reason sql.NullString
}

func (q *Queries) UpsertInvalidFile(ctx context.Context, arg UpsertInvalidFileParams) error {
	_, err := q.exec(ctx, q.upsertInvalidFileStmt, upsertInvalidFile,
		arg.Path,
		arg.Mtime,
		arg.Size,
		arg.Reason,
	)
	return err
}
