// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: iptc.sql

package gallerydb

import (
	"context"
	"database/sql"
)

const deleteIPTC = `-- name: DeleteIPTC :exec
DELETE FROM iptc_metadata WHERE file_id = ?
`

func (q *Queries) DeleteIPTC(ctx context.Context, fileID int64) error {
	_, err := q.exec(ctx, q.deleteIPTCStmt, deleteIPTC, fileID)
	return err
}

const deleteIPTCKeyword = `-- name: DeleteIPTCKeyword :exec
DELETE FROM iptc_keywords WHERE id = ?
`

func (q *Queries) DeleteIPTCKeyword(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteIPTCKeywordStmt, deleteIPTCKeyword, id)
	return err
}

const getIPTCByFile = `-- name: GetIPTCByFile :one
SELECT file_id, title, description, keywords, creator, copyright, credit, source, created_date FROM iptc_metadata WHERE file_id = ?
`

func (q *Queries) GetIPTCByFile(ctx context.Context, fileID int64) (IptcMetadatum, error) {
	row := q.queryRow(ctx, q.getIPTCByFileStmt, getIPTCByFile, fileID)
	var i IptcMetadatum
	err := row.Scan(
		&i.FileID,
		&i.Title,
		&i.Description,
		&i.Keywords,
		&i.Creator,
		&i.Copyright,
		&i.Credit,
		&i.Source,
		&i.CreatedDate,
	)
	return i, err
}

const getIPTCKeywords = `-- name: GetIPTCKeywords :many
SELECT id, file_id, keyword FROM iptc_keywords WHERE file_id = ?
`

func (q *Queries) GetIPTCKeywords(ctx context.Context, fileID int64) ([]IptcKeyword, error) {
	rows, err := q.query(ctx, q.getIPTCKeywordsStmt, getIPTCKeywords, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IptcKeyword
	for rows.Next() {
		var i IptcKeyword
		if err := rows.Scan(&i.ID, &i.FileID, &i.Keyword); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertIPTCKeyword = `-- name: InsertIPTCKeyword :exec
INSERT INTO iptc_keywords (id, file_id, keyword)
VALUES (?, ?, ?)
`

type InsertIPTCKeywordParams struct {
	ID      int64
	FileID  int64
	Keyword string
}

func (q *Queries) InsertIPTCKeyword(ctx context.Context, arg InsertIPTCKeywordParams) error {
	_, err := q.exec(ctx, q.insertIPTCKeywordStmt, insertIPTCKeyword, arg.ID, arg.FileID, arg.Keyword)
	return err
}

const upsertIPTC = `-- name: UpsertIPTC :exec
INSERT INTO iptc_metadata (file_id, title, description, keywords, creator,
                           copyright, credit, source, created_date)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(file_id) DO UPDATE SET
  title=excluded.title,
  description=excluded.description,
  keywords=excluded.keywords,
  creator=excluded.creator,
  copyright=excluded.copyright,
  credit=excluded.credit,
  source=excluded.source,
  created_date=excluded.created_date
`

type UpsertIPTCParams struct {
	FileID      int64
	Title       sql.NullString
	Description sql.NullString
	Keywords    sql.NullString
	Creator     sql.NullString
	Copyright   sql.NullString
	Credit      sql.NullString
	Source      sql.NullString
	CreatedDate sql.NullInt64
}

func (q *Queries) UpsertIPTC(ctx context.Context, arg UpsertIPTCParams) error {
	_, err := q.exec(ctx, q.upsertIPTCStmt, upsertIPTC,
		arg.FileID,
		arg.Title,
		arg.Description,
		arg.Keywords,
		arg.Creator,
		arg.Copyright,
		arg.Credit,
		arg.Source,
		arg.CreatedDate,
	)
	return err
}
