// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login_attempts.sql

package gallerydb

import (
	"context"
	"database/sql"
)

const clearLoginAttempts = `-- name: ClearLoginAttempts :exec
DELETE FROM login_attempts WHERE username = ?
`

func (q *Queries) ClearLoginAttempts(ctx context.Context, username string) error {
	_, err := q.exec(ctx, q.clearLoginAttemptsStmt, clearLoginAttempts, username)
	return err
}

const getLoginAttempt = `-- name: GetLoginAttempt :one
SELECT username, failed_attempts, locked_until, last_attempt_at
FROM login_attempts
WHERE username = ?
`

func (q *Queries) GetLoginAttempt(ctx context.Context, username string) (LoginAttempt, error) {
	row := q.queryRow(ctx, q.getLoginAttemptStmt, getLoginAttempt, username)
	var i LoginAttempt
	err := row.Scan(
		&i.Username,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastAttemptAt,
	)
	return i, err
}

const unlockAccount = `-- name: UnlockAccount :exec
UPDATE login_attempts
SET failed_attempts = 0, locked_until = NULL
WHERE username = ?
`

func (q *Queries) UnlockAccount(ctx context.Context, username string) error {
	_, err := q.exec(ctx, q.unlockAccountStmt, unlockAccount, username)
	return err
}

const upsertLoginAttempt = `-- name: UpsertLoginAttempt :exec
INSERT INTO login_attempts (username, failed_attempts, last_attempt_at, locked_until)
VALUES (?, ?, ?, ?)
ON CONFLICT(username) DO UPDATE SET
  failed_attempts = excluded.failed_attempts,
  last_attempt_at = excluded.last_attempt_at,
  locked_until = excluded.locked_until
`

type UpsertLoginAttemptParams struct {
	Username       string
	FailedAttempts int64
	LastAttemptAt  int64
	LockedUntil    sql.NullInt64
}

func (q *Queries) UpsertLoginAttempt(ctx context.Context, arg UpsertLoginAttemptParams) error {
	_, err := q.exec(ctx, q.upsertLoginAttemptStmt, upsertLoginAttempt,
		arg.Username,
		arg.FailedAttempts,
		arg.LastAttemptAt,
		arg.LockedUntil,
	)
	return err
}
