// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gallerydb

import (
	"database/sql"
)

type Config struct {
	Key             string
	Value           string
	CreatedAt       interface{}
	UpdatedAt       interface{}
	Type            sql.NullString
	Category        sql.NullString
	RequiresRestart int64
	Description     sql.NullString
	DefaultValue    sql.NullString
	HelpText        sql.NullString
	ExampleValue    sql.NullString
}

type ExifMetadatum struct {
	FileID       int64
	CameraMake   sql.NullString
	CameraModel  sql.NullString
	LensModel    sql.NullString
	FocalLength  sql.NullString
	Aperture     sql.NullString
	ShutterSpeed sql.NullString
	Iso          sql.NullInt64
	Orientation  sql.NullInt64
	Latitude     sql.NullFloat64
	Longitude    sql.NullFloat64
	Altitude     sql.NullFloat64
	CaptureDate  sql.NullInt64
	Software     sql.NullString
}

type File struct {
	ID        int64
	FolderID  sql.NullInt64
	PathID    int64
	Filename  string
	SizeBytes sql.NullInt64
	Mtime     sql.NullInt64
	Md5       sql.NullString
	Phash     sql.NullInt64
	MimeType  sql.NullString
	Width     sql.NullInt64
	Height    sql.NullInt64
	CreatedAt interface{}
	UpdatedAt interface{}
}

type FilePath struct {
	ID   int64
	Path string
}

type FileView struct {
	ID         int64
	FolderID   sql.NullInt64
	FolderPath sql.NullString
	Path       string
	Filename   string
	SizeBytes  sql.NullInt64
	Mtime      sql.NullInt64
	Md5        sql.NullString
	Phash      sql.NullInt64
	MimeType   sql.NullString
	Width      sql.NullInt64
	Height     sql.NullInt64
	CreatedAt  interface{}
	UpdatedAt  interface{}
}

type Folder struct {
	ID        int64
	ParentID  sql.NullInt64
	PathID    int64
	Name      string
	Mtime     sql.NullInt64
	TileID    sql.NullInt64
	CreatedAt interface{}
	UpdatedAt interface{}
}

type FolderPath struct {
	ID   int64
	Path string
}

type FolderTileExistsView struct {
	Path  string
	ID    int64
	Found bool
}

type FolderView struct {
	ID        int64
	ParentID  sql.NullInt64
	Path      string
	Name      string
	Mtime     sql.NullInt64
	CreatedAt interface{}
	UpdatedAt interface{}
}

type HttpCache struct {
	ID              int64
	Key             string
	Method          string
	Path            string
	QueryString     sql.NullString
	Encoding        string
	Status          int64
	ContentType     sql.NullString
	CacheControl    sql.NullString
	Etag            sql.NullString
	LastModified    sql.NullString
	Vary            sql.NullString
	Body            []byte
	ContentLength   sql.NullInt64
	CreatedAt       int64
	ExpiresAt       sql.NullInt64
	ContentEncoding sql.NullString
}

type InvalidFile struct {
	Path      string
	Mtime     int64
	Size      int64
	Reason    sql.NullString
	CreatedAt int64
	UpdatedAt int64
}

type IptcKeyword struct {
	ID      int64
	FileID  int64
	Keyword string
}

type IptcMetadatum struct {
	FileID      int64
	Title       sql.NullString
	Description sql.NullString
	Keywords    sql.NullString
	Creator     sql.NullString
	Copyright   sql.NullString
	Credit      sql.NullString
	Source      sql.NullString
	CreatedDate sql.NullInt64
}

type LoginAttempt struct {
	Username       string
	FailedAttempts int64
	LockedUntil    sql.NullInt64
	LastAttemptAt  int64
}

type ModuleState struct {
	Name           string
	IsActive       int64
	LastStartedAt  sql.NullInt64
	LastFinishedAt sql.NullInt64
}

type QcFilePathSubsetFileName struct {
	Filename string
	Path     string
}

type QcFolderPathSubsetFilePath struct {
	FolderPath string
	FilePath   string
}

type Thumbnail struct {
	ID        int64
	FileID    int64
	SizeLabel string
	Width     int64
	Height    int64
	Format    string
	CreatedAt interface{}
	UpdatedAt interface{}
}

type ThumbnailExistsView struct {
	Path  string
	ID    int64
	Found bool
}

type XmpProperty struct {
	ID        int64
	FileID    int64
	Namespace string
	Property  string
	Value     sql.NullString
}

type XmpRaw struct {
	FileID int64
	RawXml sql.NullString
}
