// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: module_state.sql

package gallerydb

import (
	"context"
	"database/sql"
)

const getModuleState = `-- name: GetModuleState :one
SELECT name, is_active, last_started_at, last_finished_at
FROM module_state
WHERE name = ?
`

func (q *Queries) GetModuleState(ctx context.Context, name string) (ModuleState, error) {
	row := q.queryRow(ctx, q.getModuleStateStmt, getModuleState, name)
	var i ModuleState
	err := row.Scan(
		&i.Name,
		&i.IsActive,
		&i.LastStartedAt,
		&i.LastFinishedAt,
	)
	return i, err
}

const setModuleState = `-- name: SetModuleState :exec
INSERT INTO module_state (name, is_active, last_started_at, last_finished_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
  is_active = excluded.is_active,
  last_started_at = COALESCE(excluded.last_started_at, module_state.last_started_at),
  last_finished_at = COALESCE(excluded.last_finished_at, module_state.last_finished_at)
`

type SetModuleStateParams struct {
	Name           string
	IsActive       int64
	LastStartedAt  sql.NullInt64
	LastFinishedAt sql.NullInt64
}

func (q *Queries) SetModuleState(ctx context.Context, arg SetModuleStateParams) error {
	_, err := q.exec(ctx, q.setModuleStateStmt, setModuleState,
		arg.Name,
		arg.IsActive,
		arg.LastStartedAt,
		arg.LastFinishedAt,
	)
	return err
}
