// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gallerydb

import (
	"context"
	"database/sql"
)

type Querier interface {
	ClearHttpCache(ctx context.Context) error
	ClearLoginAttempts(ctx context.Context, username string) error
	CountHttpCacheEntries(ctx context.Context) (int64, error)
	DeleteHttpCacheByID(ctx context.Context, id int64) error
	DeleteHttpCacheByKey(ctx context.Context, key string) error
	DeleteHttpCacheExpired(ctx context.Context) error
	DeleteIPTC(ctx context.Context, fileID int64) error
	DeleteIPTCKeyword(ctx context.Context, id int64) error
	DeleteInvalidFileByPath(ctx context.Context, path string) error
	DeleteXMPProperty(ctx context.Context, id int64) error
	DeleteXMPRaw(ctx context.Context, fileID int64) error
	GetConfigValueByKey(ctx context.Context, key string) (string, error)
	GetConfigs(ctx context.Context) ([]Config, error)
	GetExifByFile(ctx context.Context, fileID int64) (ExifMetadatum, error)
	GetFileByPath(ctx context.Context, path string) (File, error)
	GetFileViewByID(ctx context.Context, id int64) (FileView, error)
	GetFileViewsByFolderIDOrderByFileName(ctx context.Context, folderID sql.NullInt64) ([]FileView, error)
	// -- name: PopulateMissingTileID :exec
	// UPDATE folders
	//    SET tile_id = (
	//      SELECT tile_id
	//        FROM (
	//          SELECT f.id, p.id AS tile_id
	//               , DENSE_RANK() OVER (PARTITION BY f.id ORDER BY p.path) AS rnk
	//            FROM files f
	//                 INNER JOIN file_paths p
	//                   ON f.path_id = p.id
	//           WHERE f.tile_id IS NULL
	//        ) ranked
	//       WHERE ranked.id = folders.id
	//         AND ranked.rnk = 1
	//    )
	//  WHERE EXISTS (
	//      SELECT 1 FROM files f
	//      WHERE f.tile_id IS NULL AND folders.id = f.id
	//    );
	GetFolderByID(ctx context.Context, id int64) (Folder, error)
	GetFolderByPath(ctx context.Context, path string) (Folder, error)
	GetFolderIDByPath(ctx context.Context, path string) (int64, error)
	GetFolderTileExistsViewByPath(ctx context.Context, path string) (bool, error)
	GetFolderViewByID(ctx context.Context, id int64) (FolderView, error)
	GetFoldersViewsByParentIDOrderByName(ctx context.Context, parentID sql.NullInt64) ([]FolderView, error)
	// queries for HTTP cache table operations
	GetHttpCacheByKey(ctx context.Context, key string) (HttpCache, error)
	GetHttpCacheOldestCreated(ctx context.Context, limit int64) ([]GetHttpCacheOldestCreatedRow, error)
	GetHttpCacheSizeBytes(ctx context.Context) (interface{}, error)
	GetIPTCByFile(ctx context.Context, fileID int64) (IptcMetadatum, error)
	GetIPTCKeywords(ctx context.Context, fileID int64) ([]IptcKeyword, error)
	GetInvalidFileByPath(ctx context.Context, path string) (InvalidFile, error)
	GetLoginAttempt(ctx context.Context, username string) (LoginAttempt, error)
	GetThumbnailBlobDataByID(ctx context.Context, thumbnailID int64) ([]byte, error)
	GetThumbnailExistsViewByID(ctx context.Context, id int64) (bool, error)
	GetThumbnailsByFileID(ctx context.Context, fileID int64) (Thumbnail, error)
	GetXMPPropertiesByFile(ctx context.Context, fileID int64) ([]XmpProperty, error)
	GetXMPRaw(ctx context.Context, fileID int64) (XmpRaw, error)
	HttpCacheExistsByKey(ctx context.Context, key string) (int64, error)
	InsertIPTCKeyword(ctx context.Context, arg InsertIPTCKeywordParams) error
	UnlockAccount(ctx context.Context, username string) error
	UpdateFolderTileId(ctx context.Context, arg UpdateFolderTileIdParams) error
	UpsertConfigValueOnly(ctx context.Context, arg UpsertConfigValueOnlyParams) error
	UpsertExif(ctx context.Context, arg UpsertExifParams) error
	UpsertFilePathReturningID(ctx context.Context, path string) (int64, error)
	UpsertFileReturningFile(ctx context.Context, arg UpsertFileReturningFileParams) (File, error)
	UpsertFolderPathReturningID(ctx context.Context, path string) (int64, error)
	UpsertFolderReturningFolder(ctx context.Context, arg UpsertFolderReturningFolderParams) (Folder, error)
	UpsertHttpCache(ctx context.Context, arg UpsertHttpCacheParams) error
	UpsertIPTC(ctx context.Context, arg UpsertIPTCParams) error
	UpsertInvalidFile(ctx context.Context, arg UpsertInvalidFileParams) error
	UpsertLoginAttempt(ctx context.Context, arg UpsertLoginAttemptParams) error
	UpsertThumbnailBlob(ctx context.Context, arg UpsertThumbnailBlobParams) error
	UpsertThumbnailReturningID(ctx context.Context, arg UpsertThumbnailReturningIDParams) (int64, error)
	UpsertXMPProperty(ctx context.Context, arg UpsertXMPPropertyParams) error
	UpsertXMPRaw(ctx context.Context, arg UpsertXMPRawParams) error
}

var _ Querier = (*Queries)(nil)
