// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: thumbnails.sql

package gallerydb

import (
	"context"
)

const getThumbnailExistsViewByID = `-- name: GetThumbnailExistsViewByID :one
SELECT found 
  FROM thumbnail_exists_view
 WHERE id = ?
`

func (q *Queries) GetThumbnailExistsViewByID(ctx context.Context, id int64) (bool, error) {
	row := q.queryRow(ctx, q.getThumbnailExistsViewByIDStmt, getThumbnailExistsViewByID, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const getThumbnailsByFileID = `-- name: GetThumbnailsByFileID :one
SELECT id, file_id, size_label, width, height, format, created_at, updated_at 
  FROM thumbnails 
 WHERE file_id = ?
`

func (q *Queries) GetThumbnailsByFileID(ctx context.Context, fileID int64) (Thumbnail, error) {
	row := q.queryRow(ctx, q.getThumbnailsByFileIDStmt, getThumbnailsByFileID, fileID)
	var i Thumbnail
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.SizeLabel,
		&i.Width,
		&i.Height,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertThumbnailReturningID = `-- name: UpsertThumbnailReturningID :one
INSERT INTO thumbnails (file_id, size_label, width, height, format, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
    ON CONFLICT(id) 
    DO UPDATE 
          SET file_id    = excluded.file_id
            , size_label = excluded.size_label
            , width      = excluded.width
            , height     = excluded.height
            , format     = excluded.format
            , updated_at = excluded.updated_at
        WHERE file_id    IS NOT excluded.file_id
           OR size_label IS NOT excluded.size_label
           OR width      IS NOT excluded.width
           OR height     IS NOT excluded.height
           OR format     IS NOT excluded.format
RETURNING id
`

type UpsertThumbnailReturningIDParams struct {
	FileID    int64
	SizeLabel string
	Width     int64
	Height    int64
	Format    string
	CreatedAt interface{}
	UpdatedAt interface{}
}

func (q *Queries) UpsertThumbnailReturningID(ctx context.Context, arg UpsertThumbnailReturningIDParams) (int64, error) {
	row := q.queryRow(ctx, q.upsertThumbnailReturningIDStmt, upsertThumbnailReturningID,
		arg.FileID,
		arg.SizeLabel,
		arg.Width,
		arg.Height,
		arg.Format,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
