// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: xmp.sql

package gallerydb

import (
	"context"
	"database/sql"
)

const deleteXMPProperty = `-- name: DeleteXMPProperty :exec
DELETE FROM xmp_properties WHERE id = ?
`

func (q *Queries) DeleteXMPProperty(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteXMPPropertyStmt, deleteXMPProperty, id)
	return err
}

const deleteXMPRaw = `-- name: DeleteXMPRaw :exec
DELETE FROM xmp_raw WHERE file_id = ?
`

func (q *Queries) DeleteXMPRaw(ctx context.Context, fileID int64) error {
	_, err := q.exec(ctx, q.deleteXMPRawStmt, deleteXMPRaw, fileID)
	return err
}

const getXMPPropertiesByFile = `-- name: GetXMPPropertiesByFile :many
SELECT id, file_id, namespace, property, value FROM xmp_properties WHERE file_id = ?
`

func (q *Queries) GetXMPPropertiesByFile(ctx context.Context, fileID int64) ([]XmpProperty, error) {
	rows, err := q.query(ctx, q.getXMPPropertiesByFileStmt, getXMPPropertiesByFile, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []XmpProperty
	for rows.Next() {
		var i XmpProperty
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.Namespace,
			&i.Property,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getXMPRaw = `-- name: GetXMPRaw :one
SELECT file_id, raw_xml FROM xmp_raw WHERE file_id = ?
`

func (q *Queries) GetXMPRaw(ctx context.Context, fileID int64) (XmpRaw, error) {
	row := q.queryRow(ctx, q.getXMPRawStmt, getXMPRaw, fileID)
	var i XmpRaw
	err := row.Scan(&i.FileID, &i.RawXml)
	return i, err
}

const upsertXMPProperty = `-- name: UpsertXMPProperty :exec
INSERT INTO xmp_properties (id, file_id, namespace, property, value)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  file_id=excluded.file_id,
  namespace=excluded.namespace,
  property=excluded.property,
  value=excluded.value
`

type UpsertXMPPropertyParams struct {
	ID        int64
	FileID    int64
	Namespace string
	Property  string
	Value     sql.NullString
}

func (q *Queries) UpsertXMPProperty(ctx context.Context, arg UpsertXMPPropertyParams) error {
	_, err := q.exec(ctx, q.upsertXMPPropertyStmt, upsertXMPProperty,
		arg.ID,
		arg.FileID,
		arg.Namespace,
		arg.Property,
		arg.Value,
	)
	return err
}

const upsertXMPRaw = `-- name: UpsertXMPRaw :exec
INSERT INTO xmp_raw (file_id, raw_xml)
VALUES (?, ?)
ON CONFLICT(file_id) DO UPDATE SET raw_xml=excluded.raw_xml
`

type UpsertXMPRawParams struct {
	FileID int64
	RawXml sql.NullString
}

func (q *Queries) UpsertXMPRaw(ctx context.Context, arg UpsertXMPRawParams) error {
	_, err := q.exec(ctx, q.upsertXMPRawStmt, upsertXMPRaw, arg.FileID, arg.RawXml)
	return err
}
